version: "3"

services:
  app:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks: 
      - my-net
    depends_on: 
      - db
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: classroom_booking
    expose:  
      - "5432"
    networks:
      - my-net

networks:
  my-net:
    driver: bridge