// <auto-generated />
using System;
using ClassroomBooking.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClassroomBooking.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240221060018_UpdateUser")]
    partial class UpdateUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.Classroom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Building")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Classrooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("382201d9-a550-455c-971c-f577c8e0c6b5"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3070),
                            Number = 200
                        },
                        new
                        {
                            Id = new Guid("d20148eb-0aa9-454f-8970-4fa618878da7"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3080),
                            Number = 201
                        },
                        new
                        {
                            Id = new Guid("a59747a1-3119-4a44-849a-1e1174572b42"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3090),
                            Number = 202
                        },
                        new
                        {
                            Id = new Guid("c2bc5fb1-11ea-468f-bcbe-89d67e230dac"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3090),
                            Number = 203
                        },
                        new
                        {
                            Id = new Guid("8860271b-6643-4bbd-ba3a-95db6ec13601"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3090),
                            Number = 204
                        },
                        new
                        {
                            Id = new Guid("87343992-8b83-4d4f-949d-69d8e455c5b7"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3100),
                            Number = 205
                        },
                        new
                        {
                            Id = new Guid("b46f9277-d5bc-4d59-a9df-88f6c7c66a53"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3100),
                            Number = 206
                        },
                        new
                        {
                            Id = new Guid("c7db2e00-5bb2-40a1-9521-c49b13414ccb"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3100),
                            Number = 207
                        },
                        new
                        {
                            Id = new Guid("ae3ab806-f022-4d85-89a5-56df7f9fa476"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3100),
                            Number = 208
                        },
                        new
                        {
                            Id = new Guid("8b916998-a637-46c4-bcc7-ee68afcecf2e"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3110),
                            Number = 209
                        },
                        new
                        {
                            Id = new Guid("0a7614eb-6b8e-4535-83e7-ea1840b2cb69"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3110),
                            Number = 210
                        },
                        new
                        {
                            Id = new Guid("a9e6e82b-a0f8-4141-afc4-ca58f6ca57b9"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3110),
                            Number = 200
                        },
                        new
                        {
                            Id = new Guid("e9d2a4d1-e50a-4d2f-acba-664153e70b47"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3110),
                            Number = 201
                        },
                        new
                        {
                            Id = new Guid("a9aae60f-66e2-47c4-b754-90599028dd94"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3120),
                            Number = 202
                        },
                        new
                        {
                            Id = new Guid("3df4c99f-a847-46cb-8d15-5ac3840d29de"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3120),
                            Number = 203
                        },
                        new
                        {
                            Id = new Guid("3ffd6a1d-e314-43e9-837f-43a0a24b5125"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3140),
                            Number = 204
                        },
                        new
                        {
                            Id = new Guid("e0f95b7d-cf1f-4646-afe7-efdec1dff622"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3150),
                            Number = 205
                        },
                        new
                        {
                            Id = new Guid("cd58adfc-0ac3-4ca1-86f3-823c7cacea4d"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3150),
                            Number = 206
                        },
                        new
                        {
                            Id = new Guid("00f5048c-7ca7-47e0-b4e4-519d7d38585a"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3150),
                            Number = 207
                        },
                        new
                        {
                            Id = new Guid("36ec9f63-a8d4-4339-95a3-bd7354e01cbb"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3150),
                            Number = 208
                        },
                        new
                        {
                            Id = new Guid("83120be8-719c-408e-81e8-41e2bf831da5"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3160),
                            Number = 209
                        },
                        new
                        {
                            Id = new Guid("0ec09a0a-2b49-4d07-a4fe-c4fa849d4f04"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3160),
                            Number = 210
                        },
                        new
                        {
                            Id = new Guid("3b3dddd4-14c5-4b0d-b277-03d1c99b0839"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3160),
                            Number = 200
                        },
                        new
                        {
                            Id = new Guid("3e319269-dd87-4fb5-8146-8b9c928afb48"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3160),
                            Number = 201
                        },
                        new
                        {
                            Id = new Guid("328b65ab-b9a8-4d7b-b67d-d4064f29b7d7"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3160),
                            Number = 202
                        },
                        new
                        {
                            Id = new Guid("56003ef4-85ff-4127-8db6-839fd1882068"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3170),
                            Number = 203
                        },
                        new
                        {
                            Id = new Guid("8a8fe441-abbb-4caf-8b51-ef6eefd3ada0"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3170),
                            Number = 204
                        },
                        new
                        {
                            Id = new Guid("d16d5c71-984c-4bb8-a8c8-0c3fb1f41911"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3170),
                            Number = 205
                        },
                        new
                        {
                            Id = new Guid("d6ed42ce-e35b-4803-bdb1-5655fee86c5c"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3170),
                            Number = 206
                        },
                        new
                        {
                            Id = new Guid("6beafe6a-80ea-40c1-af29-b1423c556fd4"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3180),
                            Number = 207
                        },
                        new
                        {
                            Id = new Guid("87c88538-2034-454f-a644-5cc34e38447b"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3180),
                            Number = 208
                        },
                        new
                        {
                            Id = new Guid("fd046374-db42-44b7-9132-2f63b0130745"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3180),
                            Number = 209
                        },
                        new
                        {
                            Id = new Guid("5b4f92e6-e0ee-425f-99d4-7f4c55a01eef"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3180),
                            Number = 210
                        },
                        new
                        {
                            Id = new Guid("230d12ae-426b-4ca8-a14b-a462b2fb23b6"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3190),
                            Number = 200
                        },
                        new
                        {
                            Id = new Guid("6530f6f4-2480-4e11-91d5-7dd0b8c33991"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3190),
                            Number = 201
                        },
                        new
                        {
                            Id = new Guid("4f4954cf-dc1b-4d22-89e3-a4517af03873"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3190),
                            Number = 202
                        },
                        new
                        {
                            Id = new Guid("86c8901b-a053-454b-93c6-3f39c9f48e4f"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3190),
                            Number = 203
                        },
                        new
                        {
                            Id = new Guid("5b414d2a-ea80-4a9b-896e-b7b606e9e433"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3190),
                            Number = 204
                        },
                        new
                        {
                            Id = new Guid("725291a7-6b33-4d90-8b02-423d7af5efa0"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3200),
                            Number = 205
                        },
                        new
                        {
                            Id = new Guid("7b59fef0-ada2-4422-bc3c-8d2a7e5cbca7"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3200),
                            Number = 206
                        },
                        new
                        {
                            Id = new Guid("cfa547f1-d796-47fc-93b5-e6a79ed29f2e"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3200),
                            Number = 207
                        },
                        new
                        {
                            Id = new Guid("e2808f31-ccdc-46c8-a3a0-7b29238b8547"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3200),
                            Number = 208
                        },
                        new
                        {
                            Id = new Guid("decae0e9-b342-4752-87af-ba8f984043dd"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3210),
                            Number = 209
                        },
                        new
                        {
                            Id = new Guid("c2899ddd-6dad-4830-8aa4-8b27a3da6c3c"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3210),
                            Number = 210
                        },
                        new
                        {
                            Id = new Guid("78ccfbd3-c7ec-4778-b2ff-31bf5c2bd04c"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3210),
                            Number = 200
                        },
                        new
                        {
                            Id = new Guid("6e3037b7-f4b3-4e1a-8c57-d565304149cb"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3210),
                            Number = 201
                        },
                        new
                        {
                            Id = new Guid("c495f6e4-3084-45d4-914e-16d85b2f975d"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3210),
                            Number = 202
                        },
                        new
                        {
                            Id = new Guid("754641b5-0ac7-4fde-8532-6e114eb99e59"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3220),
                            Number = 203
                        },
                        new
                        {
                            Id = new Guid("1892e641-2800-4ba5-b9a4-4d07d38f08fa"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3220),
                            Number = 204
                        },
                        new
                        {
                            Id = new Guid("8e2d51db-9b09-4029-ba8c-9ebc6680bffc"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3220),
                            Number = 205
                        },
                        new
                        {
                            Id = new Guid("ca1f9b58-4f98-4dc6-8a31-47263c7dc1db"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3220),
                            Number = 206
                        },
                        new
                        {
                            Id = new Guid("7462a661-17d9-4b03-8c71-b43c6f6d8bf7"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3230),
                            Number = 207
                        },
                        new
                        {
                            Id = new Guid("dbcdf608-e147-42a1-b1f7-736fcd156d8f"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3230),
                            Number = 208
                        },
                        new
                        {
                            Id = new Guid("4da145d2-9309-4fff-bfb3-05f574f047a4"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3230),
                            Number = 209
                        },
                        new
                        {
                            Id = new Guid("d01051cd-37e2-41ba-800a-d8cd59a0156b"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3230),
                            Number = 210
                        });
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.Key", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KeyStatus")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("UserId");

                    b.ToTable("Keys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("37a639f1-6ddc-4716-866c-7796a64d9152"),
                            ClassroomId = new Guid("382201d9-a550-455c-971c-f577c8e0c6b5"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3370),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("6ee763e5-8231-4a1b-8ce9-8a5fc9703f0c"),
                            ClassroomId = new Guid("d20148eb-0aa9-454f-8970-4fa618878da7"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3370),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("445853fa-98ec-4369-9cb6-ab02d214a518"),
                            ClassroomId = new Guid("a59747a1-3119-4a44-849a-1e1174572b42"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3380),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("78ddf92f-dfc8-4ab4-8461-8440f2c19da6"),
                            ClassroomId = new Guid("c2bc5fb1-11ea-468f-bcbe-89d67e230dac"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3380),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("764cf89e-af4c-49bd-9494-4b489fcca9e6"),
                            ClassroomId = new Guid("8860271b-6643-4bbd-ba3a-95db6ec13601"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3380),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("de8d4710-d74c-404c-bbcb-1368038beb9e"),
                            ClassroomId = new Guid("87343992-8b83-4d4f-949d-69d8e455c5b7"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3390),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("5a238935-6d18-4e97-a5c0-d80678fb6ae1"),
                            ClassroomId = new Guid("b46f9277-d5bc-4d59-a9df-88f6c7c66a53"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3390),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("31d9e016-c4e9-4886-80c3-b712cdac65b5"),
                            ClassroomId = new Guid("c7db2e00-5bb2-40a1-9521-c49b13414ccb"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3390),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("32c7ad59-ebf9-467b-916d-6787fd90227c"),
                            ClassroomId = new Guid("ae3ab806-f022-4d85-89a5-56df7f9fa476"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3390),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("e8c46283-fc0b-461d-ae77-302eaddefb7e"),
                            ClassroomId = new Guid("8b916998-a637-46c4-bcc7-ee68afcecf2e"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3400),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("a816b8c7-0445-4215-8da5-b89b537a04d0"),
                            ClassroomId = new Guid("0a7614eb-6b8e-4535-83e7-ea1840b2cb69"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3400),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("5b18d3d6-9cfb-433b-a1e5-af3cc19196c2"),
                            ClassroomId = new Guid("a9e6e82b-a0f8-4141-afc4-ca58f6ca57b9"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3400),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("8dd0f4ec-3d23-4cbf-9c67-82632afde3b6"),
                            ClassroomId = new Guid("e9d2a4d1-e50a-4d2f-acba-664153e70b47"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3400),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("2c0c5b5b-6034-4d1c-b820-d9ab158ff339"),
                            ClassroomId = new Guid("a9aae60f-66e2-47c4-b754-90599028dd94"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3400),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("94ef932e-991c-431a-8970-edb2590a7712"),
                            ClassroomId = new Guid("3df4c99f-a847-46cb-8d15-5ac3840d29de"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3410),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("ee8c6a23-2139-4b90-8fb4-91fa5233519e"),
                            ClassroomId = new Guid("3ffd6a1d-e314-43e9-837f-43a0a24b5125"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3410),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("de3d8e46-e163-4b50-b24a-ed0ed6c31517"),
                            ClassroomId = new Guid("e0f95b7d-cf1f-4646-afe7-efdec1dff622"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3410),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("74342e43-1d87-473a-946e-bb606348a5c0"),
                            ClassroomId = new Guid("cd58adfc-0ac3-4ca1-86f3-823c7cacea4d"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3420),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("3871ce02-12be-4bd8-ae2c-56d368ec6c6c"),
                            ClassroomId = new Guid("00f5048c-7ca7-47e0-b4e4-519d7d38585a"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3420),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("6c295068-a26a-4372-93fa-3b23cc91e923"),
                            ClassroomId = new Guid("36ec9f63-a8d4-4339-95a3-bd7354e01cbb"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3420),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("61113940-5ac8-490f-b9b8-fd613cbdaccf"),
                            ClassroomId = new Guid("83120be8-719c-408e-81e8-41e2bf831da5"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3420),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("11b5f620-db15-40c7-a060-29da89dd83a2"),
                            ClassroomId = new Guid("0ec09a0a-2b49-4d07-a4fe-c4fa849d4f04"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3420),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("0b334365-e750-482b-a3d1-3c6f8de585c8"),
                            ClassroomId = new Guid("3b3dddd4-14c5-4b0d-b277-03d1c99b0839"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3430),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("7e2a925d-9026-4329-997d-6ee8de0646af"),
                            ClassroomId = new Guid("3e319269-dd87-4fb5-8146-8b9c928afb48"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3430),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("b99db684-c695-4ab5-af1d-04796755f6d7"),
                            ClassroomId = new Guid("328b65ab-b9a8-4d7b-b67d-d4064f29b7d7"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3430),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("9af34bb8-0cb5-49f3-9be7-2234894a03b0"),
                            ClassroomId = new Guid("56003ef4-85ff-4127-8db6-839fd1882068"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3430),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("258aae35-d8fa-4465-a4ce-629a943cd29a"),
                            ClassroomId = new Guid("8a8fe441-abbb-4caf-8b51-ef6eefd3ada0"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3440),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("6e2a6f57-d8bc-4b99-a206-256520d5a78d"),
                            ClassroomId = new Guid("d16d5c71-984c-4bb8-a8c8-0c3fb1f41911"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3440),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("1db96860-1269-4128-b6d4-14b1d2c7d3c3"),
                            ClassroomId = new Guid("d6ed42ce-e35b-4803-bdb1-5655fee86c5c"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3440),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("d72e75b8-0706-4ab0-ba17-60b2700ae8e8"),
                            ClassroomId = new Guid("6beafe6a-80ea-40c1-af29-b1423c556fd4"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3440),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("2e587e0b-2086-4d64-aff2-6f139184de09"),
                            ClassroomId = new Guid("87c88538-2034-454f-a644-5cc34e38447b"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3450),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("f03d58a3-3ce5-4548-8009-0de374ee00dc"),
                            ClassroomId = new Guid("fd046374-db42-44b7-9132-2f63b0130745"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3450),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("f8743384-a3a2-4afa-9820-ba704709dace"),
                            ClassroomId = new Guid("5b4f92e6-e0ee-425f-99d4-7f4c55a01eef"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3450),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("5527bac5-6234-4662-ab41-34c951d441ba"),
                            ClassroomId = new Guid("230d12ae-426b-4ca8-a14b-a462b2fb23b6"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3460),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("aed84b65-8920-48d5-bc5a-d43c237e438d"),
                            ClassroomId = new Guid("6530f6f4-2480-4e11-91d5-7dd0b8c33991"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3460),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("a3ac8176-ed8c-4ac4-9597-563e080e6afa"),
                            ClassroomId = new Guid("4f4954cf-dc1b-4d22-89e3-a4517af03873"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3470),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("291e5e21-3f16-41a4-b073-973747b11850"),
                            ClassroomId = new Guid("86c8901b-a053-454b-93c6-3f39c9f48e4f"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3470),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("5f47ba72-92d0-47ef-af95-922f76278d6d"),
                            ClassroomId = new Guid("5b414d2a-ea80-4a9b-896e-b7b606e9e433"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3470),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("dd844ecb-995e-4fba-8819-65cbc7775d8e"),
                            ClassroomId = new Guid("725291a7-6b33-4d90-8b02-423d7af5efa0"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3470),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("20f22356-c6d1-4d43-82dc-0e956b82eacb"),
                            ClassroomId = new Guid("7b59fef0-ada2-4422-bc3c-8d2a7e5cbca7"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3480),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("62ca9343-d3f1-4620-840c-a7c3c8a9b24c"),
                            ClassroomId = new Guid("cfa547f1-d796-47fc-93b5-e6a79ed29f2e"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3480),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("531ddf99-f507-4258-a59c-049f5561df16"),
                            ClassroomId = new Guid("e2808f31-ccdc-46c8-a3a0-7b29238b8547"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3480),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("f589ca9b-3b73-4c53-a254-ea6e75bec13a"),
                            ClassroomId = new Guid("decae0e9-b342-4752-87af-ba8f984043dd"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3480),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("336b048a-ca45-4f32-a692-2d53e506dffd"),
                            ClassroomId = new Guid("c2899ddd-6dad-4830-8aa4-8b27a3da6c3c"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3480),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("13926103-4ef5-4f9d-8ff8-e0c1d7c4818c"),
                            ClassroomId = new Guid("78ccfbd3-c7ec-4778-b2ff-31bf5c2bd04c"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3490),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("a3321892-1ebe-4501-a3d9-7be1fb60f120"),
                            ClassroomId = new Guid("6e3037b7-f4b3-4e1a-8c57-d565304149cb"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3490),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("5650429e-3dc9-4f70-9dfd-cab4fe3ed213"),
                            ClassroomId = new Guid("c495f6e4-3084-45d4-914e-16d85b2f975d"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3490),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("62ed30c9-3c01-4dd1-bc6d-37fb2702fbb4"),
                            ClassroomId = new Guid("754641b5-0ac7-4fde-8532-6e114eb99e59"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3490),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("5050492f-d63f-4cbd-8674-77bedc3c0133"),
                            ClassroomId = new Guid("1892e641-2800-4ba5-b9a4-4d07d38f08fa"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3500),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("36576478-9fc0-4fc7-a2e7-acd74658a48d"),
                            ClassroomId = new Guid("8e2d51db-9b09-4029-ba8c-9ebc6680bffc"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3500),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("7619dfd0-b631-497a-999a-3f558b72b254"),
                            ClassroomId = new Guid("ca1f9b58-4f98-4dc6-8a31-47263c7dc1db"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3500),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("c71c8d08-60e0-406a-9d22-73f986dbc4fc"),
                            ClassroomId = new Guid("7462a661-17d9-4b03-8c71-b43c6f6d8bf7"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3500),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("d0e00479-396a-4afd-9171-793730cb8f80"),
                            ClassroomId = new Guid("dbcdf608-e147-42a1-b1f7-736fcd156d8f"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3510),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("d8f19758-a273-49d1-8eb6-ccb519fdda3a"),
                            ClassroomId = new Guid("4da145d2-9309-4fff-bfb3-05f574f047a4"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3510),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("87f08519-487d-4fe5-95cf-12e5cca10844"),
                            ClassroomId = new Guid("d01051cd-37e2-41ba-800a-d8cd59a0156b"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 312, DateTimeKind.Utc).AddTicks(3510),
                            KeyStatus = 0
                        });
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.KeyRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("UserId");

                    b.ToTable("KeyRequests");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.RegistrationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RegistrationRequests");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<int?>("UserRole")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f0c7769a-de86-49bb-9fc2-081d7acf56dd"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 0, 18, 201, DateTimeKind.Utc).AddTicks(5030),
                            Email = "admin@gmail.com",
                            FullName = "admin",
                            Gender = 0,
                            Password = "$2a$11$ALp6AdTwf2oIeV1NDj13YepdL28HPDF.nf8YcwX6u0DQKPL5HFY5y",
                            UserRole = 3
                        });
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.Key", b =>
                {
                    b.HasOne("ClassroomBooking.Domain.Entities.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassroomBooking.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Classroom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.KeyRequest", b =>
                {
                    b.HasOne("ClassroomBooking.Domain.Entities.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassroomBooking.Domain.Entities.User", "User")
                        .WithMany("Requests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.RegistrationRequest", b =>
                {
                    b.HasOne("ClassroomBooking.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.User", b =>
                {
                    b.Navigation("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
