// <auto-generated />
using System;
using ClassroomBooking.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClassroomBooking.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240310040342_UpdateTransferKeyRequest")]
    partial class UpdateTransferKeyRequest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.Classroom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Building")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Classrooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cddf78ae-b9da-4a30-baf7-0bcdbbac2a79"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6470),
                            Number = 200
                        },
                        new
                        {
                            Id = new Guid("7053ebf6-5c7e-43b5-9546-3a4da8aabff6"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6480),
                            Number = 201
                        },
                        new
                        {
                            Id = new Guid("f094201e-25a8-43fb-9d1a-ae272de862b2"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6480),
                            Number = 202
                        },
                        new
                        {
                            Id = new Guid("bf24b8ca-de67-42cc-b40c-1dd45f6729a3"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6490),
                            Number = 203
                        },
                        new
                        {
                            Id = new Guid("4c19adf9-9664-4cab-b414-776605eb6bea"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6510),
                            Number = 204
                        },
                        new
                        {
                            Id = new Guid("ed3b2c19-c3d4-4743-98ae-f5722bc1aae9"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6510),
                            Number = 205
                        },
                        new
                        {
                            Id = new Guid("629b5a2e-a283-456d-99fa-a60107e8904a"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6520),
                            Number = 206
                        },
                        new
                        {
                            Id = new Guid("6e766a8a-3312-441b-9915-aced7ff3e458"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6520),
                            Number = 207
                        },
                        new
                        {
                            Id = new Guid("bdf26201-e92a-4869-9bad-1853d4a3bec4"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6520),
                            Number = 208
                        },
                        new
                        {
                            Id = new Guid("e0be6732-e266-40f7-9158-41ddc1930311"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6520),
                            Number = 209
                        },
                        new
                        {
                            Id = new Guid("60ffb073-3f6f-4b0c-a51f-1e3939f7879f"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6520),
                            Number = 210
                        },
                        new
                        {
                            Id = new Guid("d2baac43-9f15-4ddd-b3a9-f1e26771a49c"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6530),
                            Number = 200
                        },
                        new
                        {
                            Id = new Guid("a4113603-ed92-4262-9eda-965a027db2e3"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6530),
                            Number = 201
                        },
                        new
                        {
                            Id = new Guid("9bdaec8b-28d5-4bf1-9ba3-4f4231d8f6f3"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6530),
                            Number = 202
                        },
                        new
                        {
                            Id = new Guid("e60311b7-40db-491d-8a73-11d390054df2"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6530),
                            Number = 203
                        },
                        new
                        {
                            Id = new Guid("e265e523-08f6-4352-ba9c-ab1dfae0721c"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6540),
                            Number = 204
                        },
                        new
                        {
                            Id = new Guid("e7e9f836-80cb-421d-b891-a2ded2a6909d"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6540),
                            Number = 205
                        },
                        new
                        {
                            Id = new Guid("a44615a8-9ccf-4b3e-ba5f-2a49afc6f2d6"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6540),
                            Number = 206
                        },
                        new
                        {
                            Id = new Guid("db20f722-e4cd-41db-ad8b-983668164eae"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6540),
                            Number = 207
                        },
                        new
                        {
                            Id = new Guid("234b66d4-edc9-44d2-8f96-751528bc5998"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6550),
                            Number = 208
                        },
                        new
                        {
                            Id = new Guid("614610c2-8f1c-45be-bf20-c89f79c8a36e"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6550),
                            Number = 209
                        },
                        new
                        {
                            Id = new Guid("9960d9ed-d6bc-45ef-bf9d-7d52e2401d23"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6550),
                            Number = 210
                        },
                        new
                        {
                            Id = new Guid("22f4aa08-1549-41d2-8c86-3dfab2aa49f5"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6600),
                            Number = 200
                        },
                        new
                        {
                            Id = new Guid("1df03cd7-c86f-4549-9b1c-0f808bcd435c"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6600),
                            Number = 201
                        },
                        new
                        {
                            Id = new Guid("8f2f9e28-646d-4c70-9a90-5b83bc233492"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6600),
                            Number = 202
                        },
                        new
                        {
                            Id = new Guid("3adef3f1-27e4-47c6-93da-f5f49f25ae44"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6610),
                            Number = 203
                        },
                        new
                        {
                            Id = new Guid("c6d3ea63-bf32-4ec3-8732-69cfcd186555"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6620),
                            Number = 204
                        },
                        new
                        {
                            Id = new Guid("dabddd74-37d9-4137-9e91-69644551ca24"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6620),
                            Number = 205
                        },
                        new
                        {
                            Id = new Guid("778fa6e5-de5b-4466-9549-c018b0cf2d89"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6630),
                            Number = 206
                        },
                        new
                        {
                            Id = new Guid("5b250c3c-50ee-4e36-8055-0e22628d99ec"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6630),
                            Number = 207
                        },
                        new
                        {
                            Id = new Guid("a7375a75-2472-4f89-b245-d24f220337b1"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6630),
                            Number = 208
                        },
                        new
                        {
                            Id = new Guid("b4745440-a3d5-4dad-9b4d-81e638920b51"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6640),
                            Number = 209
                        },
                        new
                        {
                            Id = new Guid("fdb6ff45-07c4-463f-b0c6-fd34ba6677c4"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6640),
                            Number = 210
                        },
                        new
                        {
                            Id = new Guid("881c7004-092a-47f3-8889-417f94c69e9a"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6640),
                            Number = 200
                        },
                        new
                        {
                            Id = new Guid("9f4019c3-43dd-4283-99bf-0b1b4e847670"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6650),
                            Number = 201
                        },
                        new
                        {
                            Id = new Guid("316ea899-9cb8-4bd0-b44b-530591b419e7"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6650),
                            Number = 202
                        },
                        new
                        {
                            Id = new Guid("ba08f84c-9f6b-4c0b-b327-d4d226e42893"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6650),
                            Number = 203
                        },
                        new
                        {
                            Id = new Guid("2eeb3459-89f2-45c3-aeca-15893e83a109"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6660),
                            Number = 204
                        },
                        new
                        {
                            Id = new Guid("62eb98ba-5494-4ff8-b1e1-285fcafd70c9"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6660),
                            Number = 205
                        },
                        new
                        {
                            Id = new Guid("d9c81a84-0c39-45a1-ac19-104846f03ae8"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6660),
                            Number = 206
                        },
                        new
                        {
                            Id = new Guid("e50eb0fa-e48f-4d99-b8b3-789d671f90b9"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6660),
                            Number = 207
                        },
                        new
                        {
                            Id = new Guid("a625ede8-243e-4f2a-9537-9eb9493d8698"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6670),
                            Number = 208
                        },
                        new
                        {
                            Id = new Guid("bc170d25-6413-4d7e-aa7c-4900cd0535c2"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6670),
                            Number = 209
                        },
                        new
                        {
                            Id = new Guid("cba64341-3dea-4f52-8d9c-4a578d5c12c8"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6670),
                            Number = 210
                        },
                        new
                        {
                            Id = new Guid("e0ab6b3a-d5ad-49e5-8484-fee592613f8c"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6680),
                            Number = 200
                        },
                        new
                        {
                            Id = new Guid("3002213c-ce71-47cc-bdb5-25d5c57eb498"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6680),
                            Number = 201
                        },
                        new
                        {
                            Id = new Guid("b817c1d3-e593-4be4-bce6-e78b2bee9e8d"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6680),
                            Number = 202
                        },
                        new
                        {
                            Id = new Guid("6cbba81c-46e4-485a-ad62-babe5070a538"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6680),
                            Number = 203
                        },
                        new
                        {
                            Id = new Guid("36126804-f568-4b40-9aa0-c8fd4b0a0037"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6690),
                            Number = 204
                        },
                        new
                        {
                            Id = new Guid("a67cb00f-d07f-4039-8dbb-0ff772b6519b"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6690),
                            Number = 205
                        },
                        new
                        {
                            Id = new Guid("b51fec19-2869-4f7c-98c0-94995ba897bf"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6690),
                            Number = 206
                        },
                        new
                        {
                            Id = new Guid("e53bcc9b-33e1-462e-80be-997ebd4c81c6"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6690),
                            Number = 207
                        },
                        new
                        {
                            Id = new Guid("2b96eb37-9871-479d-917b-3791472b04a3"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6690),
                            Number = 208
                        },
                        new
                        {
                            Id = new Guid("bd00a96c-75b5-4781-870b-da2864adb4f2"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6700),
                            Number = 209
                        },
                        new
                        {
                            Id = new Guid("42014eff-8be4-4e82-9e79-57fa444ec8fc"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(6700),
                            Number = 210
                        });
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.Key", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KeyStatus")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("UserId");

                    b.ToTable("Keys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b11a622e-ce55-4d65-84ab-de2a6b454720"),
                            ClassroomId = new Guid("cddf78ae-b9da-4a30-baf7-0bcdbbac2a79"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7160),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("a47d1bda-b134-4c0e-803a-c4bc4c55fb45"),
                            ClassroomId = new Guid("7053ebf6-5c7e-43b5-9546-3a4da8aabff6"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7170),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("cdb3faea-e272-4fe6-980f-1ebcf039ee7a"),
                            ClassroomId = new Guid("f094201e-25a8-43fb-9d1a-ae272de862b2"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7170),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("5e787aea-c4f3-4471-9163-4653c7fba74a"),
                            ClassroomId = new Guid("bf24b8ca-de67-42cc-b40c-1dd45f6729a3"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7170),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("b8ebe98e-7c65-4f1c-8b6b-2972031713a5"),
                            ClassroomId = new Guid("4c19adf9-9664-4cab-b414-776605eb6bea"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7170),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("769224e4-61f4-407b-b640-f03ab6bafc62"),
                            ClassroomId = new Guid("ed3b2c19-c3d4-4743-98ae-f5722bc1aae9"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7180),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("29b51717-e62d-453c-babc-822b8c470d7d"),
                            ClassroomId = new Guid("629b5a2e-a283-456d-99fa-a60107e8904a"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7180),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("496f0c01-fbed-49a0-805a-2553a66cd132"),
                            ClassroomId = new Guid("6e766a8a-3312-441b-9915-aced7ff3e458"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7180),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("1ed38495-5ec6-4811-bb6a-c983b49adac7"),
                            ClassroomId = new Guid("bdf26201-e92a-4869-9bad-1853d4a3bec4"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7180),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("600038e1-e024-433c-9388-da7df2a136a0"),
                            ClassroomId = new Guid("e0be6732-e266-40f7-9158-41ddc1930311"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7190),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("7b6766f9-b762-4f25-bca7-35cdcac0e31e"),
                            ClassroomId = new Guid("60ffb073-3f6f-4b0c-a51f-1e3939f7879f"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7190),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("1efba1c5-c094-477a-bba4-03bb971528fe"),
                            ClassroomId = new Guid("d2baac43-9f15-4ddd-b3a9-f1e26771a49c"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7190),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("7f3b8638-adb8-4fba-b4c2-af7be65eb820"),
                            ClassroomId = new Guid("a4113603-ed92-4262-9eda-965a027db2e3"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7190),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("d5de18d7-8281-4f76-9711-a55bcaf85fef"),
                            ClassroomId = new Guid("9bdaec8b-28d5-4bf1-9ba3-4f4231d8f6f3"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7200),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("0faa77b4-2692-4f81-a60d-17cf1685b403"),
                            ClassroomId = new Guid("e60311b7-40db-491d-8a73-11d390054df2"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7200),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("b2daac8e-3392-459f-96c4-0f6eec0d2c97"),
                            ClassroomId = new Guid("e265e523-08f6-4352-ba9c-ab1dfae0721c"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7200),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("e7f6ccd5-ca96-43e9-a704-bf116be69be8"),
                            ClassroomId = new Guid("e7e9f836-80cb-421d-b891-a2ded2a6909d"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7200),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("e39e9b6b-c290-4c8a-adf7-484a64281832"),
                            ClassroomId = new Guid("a44615a8-9ccf-4b3e-ba5f-2a49afc6f2d6"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7210),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("a6bed6b4-9be8-48a5-89e5-a309d075e5f4"),
                            ClassroomId = new Guid("db20f722-e4cd-41db-ad8b-983668164eae"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7210),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("b2272c26-570d-4c9d-84b6-348b9d6e1c33"),
                            ClassroomId = new Guid("234b66d4-edc9-44d2-8f96-751528bc5998"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7210),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("397c8e39-885d-4694-a111-267a31eb71ca"),
                            ClassroomId = new Guid("614610c2-8f1c-45be-bf20-c89f79c8a36e"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7210),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("e2adf901-6df2-43a3-9c0d-7b213a8069fa"),
                            ClassroomId = new Guid("9960d9ed-d6bc-45ef-bf9d-7d52e2401d23"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7220),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("f4657f1d-6482-43e2-8d7a-d95280fc8e81"),
                            ClassroomId = new Guid("22f4aa08-1549-41d2-8c86-3dfab2aa49f5"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7220),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("906660cc-7b91-47ec-abf9-20eb4a93b1b3"),
                            ClassroomId = new Guid("1df03cd7-c86f-4549-9b1c-0f808bcd435c"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7220),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("f58093cb-792b-4c14-ab4e-a5390adecbf1"),
                            ClassroomId = new Guid("8f2f9e28-646d-4c70-9a90-5b83bc233492"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7220),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("9ed5edba-c0ab-4d2a-8a33-23281c2055e9"),
                            ClassroomId = new Guid("3adef3f1-27e4-47c6-93da-f5f49f25ae44"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7230),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("e5edf320-1028-4792-9a71-85b690e3875d"),
                            ClassroomId = new Guid("c6d3ea63-bf32-4ec3-8732-69cfcd186555"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7230),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("20d5bcd6-3e8b-4072-acc9-ddbd9c460519"),
                            ClassroomId = new Guid("dabddd74-37d9-4137-9e91-69644551ca24"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7260),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("e83cf677-c66c-4887-adac-a265977d91ad"),
                            ClassroomId = new Guid("778fa6e5-de5b-4466-9549-c018b0cf2d89"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7260),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("7cdc2e72-003a-408f-873d-ba44183a1b66"),
                            ClassroomId = new Guid("5b250c3c-50ee-4e36-8055-0e22628d99ec"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7270),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("178d8d6f-1b76-44a2-af3c-be2d9d4762e6"),
                            ClassroomId = new Guid("a7375a75-2472-4f89-b245-d24f220337b1"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7270),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("be518907-ccd3-4cb2-a0c4-53794a4c04f0"),
                            ClassroomId = new Guid("b4745440-a3d5-4dad-9b4d-81e638920b51"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7270),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("b9ea5db4-d93d-48a8-b98d-b48813bbaf2a"),
                            ClassroomId = new Guid("fdb6ff45-07c4-463f-b0c6-fd34ba6677c4"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7270),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("019bbb02-3813-4174-b8dc-4a8f73723b97"),
                            ClassroomId = new Guid("881c7004-092a-47f3-8889-417f94c69e9a"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7280),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("4cced6d5-6090-4bd0-b031-a51190a3cfb2"),
                            ClassroomId = new Guid("9f4019c3-43dd-4283-99bf-0b1b4e847670"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7280),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("1bb7a10a-1b43-43d7-ba62-d8caa5d7e04a"),
                            ClassroomId = new Guid("316ea899-9cb8-4bd0-b44b-530591b419e7"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7280),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("70b13bf2-dc87-4014-9d23-b48324386784"),
                            ClassroomId = new Guid("ba08f84c-9f6b-4c0b-b327-d4d226e42893"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7280),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("b45a88c6-93ff-4fd8-80e2-ae38279118d8"),
                            ClassroomId = new Guid("2eeb3459-89f2-45c3-aeca-15893e83a109"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7290),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("d764f8e8-3fe7-4d50-aeda-fc194b6555ba"),
                            ClassroomId = new Guid("62eb98ba-5494-4ff8-b1e1-285fcafd70c9"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7290),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("8a0ef5b6-4d78-44ba-a734-433b2439d9a0"),
                            ClassroomId = new Guid("d9c81a84-0c39-45a1-ac19-104846f03ae8"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7290),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("8825af68-aeac-4705-94c4-09612f947d82"),
                            ClassroomId = new Guid("e50eb0fa-e48f-4d99-b8b3-789d671f90b9"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7290),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("f72e4f65-f236-4eda-8891-8aa5fd9c251b"),
                            ClassroomId = new Guid("a625ede8-243e-4f2a-9537-9eb9493d8698"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7300),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("44cd6372-89e7-449a-a0a3-35207951326f"),
                            ClassroomId = new Guid("bc170d25-6413-4d7e-aa7c-4900cd0535c2"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7300),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("eb8b6cc7-2524-4d00-b170-bd91c656d73a"),
                            ClassroomId = new Guid("cba64341-3dea-4f52-8d9c-4a578d5c12c8"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7300),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("ef731c85-4a81-4afb-b660-7002c731e792"),
                            ClassroomId = new Guid("e0ab6b3a-d5ad-49e5-8484-fee592613f8c"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7300),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("72bb2f04-e7c1-4b3e-9dc8-007007c4b494"),
                            ClassroomId = new Guid("3002213c-ce71-47cc-bdb5-25d5c57eb498"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7300),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("ddf1edd8-4099-4677-865c-3f18a25dd321"),
                            ClassroomId = new Guid("b817c1d3-e593-4be4-bce6-e78b2bee9e8d"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7310),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("a22d6f7b-fca7-44ad-b0cc-ac5064b5dfc8"),
                            ClassroomId = new Guid("6cbba81c-46e4-485a-ad62-babe5070a538"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7310),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("1efd2ae6-32d6-4e67-be98-90e1ac5c22d5"),
                            ClassroomId = new Guid("36126804-f568-4b40-9aa0-c8fd4b0a0037"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7310),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("cae04adc-21d4-4baa-ba59-53e78ae3e7fb"),
                            ClassroomId = new Guid("a67cb00f-d07f-4039-8dbb-0ff772b6519b"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7320),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("1afb190e-2cc6-44dc-89db-38ff4f1a2635"),
                            ClassroomId = new Guid("b51fec19-2869-4f7c-98c0-94995ba897bf"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7320),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("9ac455d3-a60e-4c78-8598-4deb0cc07afc"),
                            ClassroomId = new Guid("e53bcc9b-33e1-462e-80be-997ebd4c81c6"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7320),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("f2a4f2d1-a8d8-434b-a01a-74e214069e1a"),
                            ClassroomId = new Guid("2b96eb37-9871-479d-917b-3791472b04a3"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7320),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("be4f79cd-9128-48c9-a6f9-17cd0d1f23f6"),
                            ClassroomId = new Guid("bd00a96c-75b5-4781-870b-da2864adb4f2"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7330),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("a221beb1-2c9b-4f3d-9e28-3d040da819ca"),
                            ClassroomId = new Guid("42014eff-8be4-4e82-9e79-57fa444ec8fc"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 42, 3, DateTimeKind.Utc).AddTicks(7330),
                            KeyStatus = 0
                        });
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.KeyRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("EndDateOfRecurrence")
                        .HasColumnType("date");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("UserId");

                    b.ToTable("KeyRequests");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.RegistrationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RegistrationRequests");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.TransferKeyRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("KeyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("KeyId");

                    b.HasIndex("RecipientId");

                    b.ToTable("TransferKeyRequests");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<int?>("UserRole")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("526dd803-83c4-431a-9211-ac30445607c6"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 41, 559, DateTimeKind.Utc).AddTicks(5650),
                            Email = "admin@gmail.com",
                            FullName = "admin",
                            Gender = 0,
                            Password = "$2a$11$yBdMeIprPipvkac.UeWiFeO9rrV8jE12xK9wTuLOgTfAs4h15ebKG",
                            UserRole = 3
                        },
                        new
                        {
                            Id = new Guid("ee057118-ee9d-4668-952c-52572fea0bf6"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 41, 670, DateTimeKind.Utc).AddTicks(1410),
                            Email = "dean@gmail.com",
                            FullName = "dean",
                            Gender = 0,
                            Password = "$2a$11$QBvCpxAB6rT2JmHNwo/MAuI/K8Hsl6R6rD7q4e62g.u1WGYRs3GeO",
                            UserRole = 2
                        },
                        new
                        {
                            Id = new Guid("9ed9b8e8-f1b4-4a3a-8ff8-c1fa07891f22"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 41, 782, DateTimeKind.Utc).AddTicks(4170),
                            Email = "teacher@gmail.com",
                            FullName = "teacher",
                            Gender = 0,
                            Password = "$2a$11$0wY22IEt8l10BKcy9LzAk.l.Qh7DbNh0QEWB05MEKk7gRQK5hHLYG",
                            UserRole = 1
                        },
                        new
                        {
                            Id = new Guid("5d209580-c292-48b0-847f-b95731dc663c"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 3, 41, 893, DateTimeKind.Utc).AddTicks(1950),
                            Email = "student@gmail.com",
                            FullName = "student",
                            Gender = 0,
                            Password = "$2a$11$ribaGKlMbDCqqkDp8L4dxetbe4tCItXAenouvsv2XPcOvmRponmJq",
                            UserRole = 0
                        });
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.Key", b =>
                {
                    b.HasOne("ClassroomBooking.Domain.Entities.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassroomBooking.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Classroom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.KeyRequest", b =>
                {
                    b.HasOne("ClassroomBooking.Domain.Entities.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassroomBooking.Domain.Entities.User", "User")
                        .WithMany("Requests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.RegistrationRequest", b =>
                {
                    b.HasOne("ClassroomBooking.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.TransferKeyRequest", b =>
                {
                    b.HasOne("ClassroomBooking.Domain.Entities.Key", "Key")
                        .WithMany()
                        .HasForeignKey("KeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassroomBooking.Domain.Entities.User", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Key");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.User", b =>
                {
                    b.Navigation("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
