// <auto-generated />
using System;
using ClassroomBooking.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClassroomBooking.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240302081955_UpdateKeyRequest")]
    partial class UpdateKeyRequest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.Classroom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Building")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Classrooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("951fca45-f944-413d-9c8c-d05da8013c7d"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(283),
                            Number = 200
                        },
                        new
                        {
                            Id = new Guid("4c401fc0-07ff-4889-9275-ad3bf078b3cc"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(307),
                            Number = 201
                        },
                        new
                        {
                            Id = new Guid("924c8721-9711-43ec-9c9a-37c5d160bd26"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(308),
                            Number = 202
                        },
                        new
                        {
                            Id = new Guid("82958cdf-cef8-4ccd-a92f-0053b26df438"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(309),
                            Number = 203
                        },
                        new
                        {
                            Id = new Guid("e37d358c-0fb7-4781-a4a7-562f8281ed51"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(310),
                            Number = 204
                        },
                        new
                        {
                            Id = new Guid("170b317f-4acb-479e-9bff-289ee5d78760"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(316),
                            Number = 205
                        },
                        new
                        {
                            Id = new Guid("816dabe8-50c0-4ee3-af20-3183c21b1da3"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(317),
                            Number = 206
                        },
                        new
                        {
                            Id = new Guid("c866080c-d5f1-4278-b91f-e6274bff4a1e"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(327),
                            Number = 207
                        },
                        new
                        {
                            Id = new Guid("2b4556ca-b0cf-45a8-b383-c0c001626b57"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(328),
                            Number = 208
                        },
                        new
                        {
                            Id = new Guid("5214f1e1-a2e2-4fe4-8272-c79f73cee851"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(329),
                            Number = 209
                        },
                        new
                        {
                            Id = new Guid("d863b8a5-0b2d-4fec-8266-d843c03b739d"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(330),
                            Number = 210
                        },
                        new
                        {
                            Id = new Guid("74a6a294-0aba-4f34-a47e-8d8b020c98b0"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(331),
                            Number = 200
                        },
                        new
                        {
                            Id = new Guid("ee487369-29ec-4b20-8980-5ec7f1ccda02"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(332),
                            Number = 201
                        },
                        new
                        {
                            Id = new Guid("376541c5-23ec-48be-a07c-bfd056662601"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(332),
                            Number = 202
                        },
                        new
                        {
                            Id = new Guid("e6e9483b-88fb-438b-a9f1-687f8583c919"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(333),
                            Number = 203
                        },
                        new
                        {
                            Id = new Guid("fe955a28-3941-41cb-b5eb-3bc36997ae72"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(336),
                            Number = 204
                        },
                        new
                        {
                            Id = new Guid("f4f238e0-af3a-45f4-bdd6-ee287c872933"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(336),
                            Number = 205
                        },
                        new
                        {
                            Id = new Guid("d7b6a32b-d978-450f-8764-2eefebe2dcc2"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(338),
                            Number = 206
                        },
                        new
                        {
                            Id = new Guid("ade295fa-7748-49d1-8d0e-d74330d2f601"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(339),
                            Number = 207
                        },
                        new
                        {
                            Id = new Guid("cd706952-6977-43e0-8ffc-6507f31b8b43"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(339),
                            Number = 208
                        },
                        new
                        {
                            Id = new Guid("9f1bf1d1-745f-46c7-a49d-105ebe35435d"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(340),
                            Number = 209
                        },
                        new
                        {
                            Id = new Guid("59c9777e-8d41-4b17-afc0-a91b154b7c3b"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(341),
                            Number = 210
                        },
                        new
                        {
                            Id = new Guid("ad3df3b9-ab8b-479c-bdb3-636434ffeb23"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(342),
                            Number = 200
                        },
                        new
                        {
                            Id = new Guid("9afb391f-f062-4081-8035-43d37934a9b5"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(344),
                            Number = 201
                        },
                        new
                        {
                            Id = new Guid("74909e27-be33-4a7a-bff5-414d6a6a76eb"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(344),
                            Number = 202
                        },
                        new
                        {
                            Id = new Guid("59357b4b-0a01-4462-b983-7ba92b2ed339"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(345),
                            Number = 203
                        },
                        new
                        {
                            Id = new Guid("3e0c04e1-aee4-4cf3-8dc2-f63f39c5154b"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(346),
                            Number = 204
                        },
                        new
                        {
                            Id = new Guid("96122a4a-3bcd-45e0-9e6f-84d444708c56"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(404),
                            Number = 205
                        },
                        new
                        {
                            Id = new Guid("0fb2adbb-19f4-47df-aacb-f49e82c71a4d"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(416),
                            Number = 206
                        },
                        new
                        {
                            Id = new Guid("0e266621-c57c-404b-9366-94069bfa4ac7"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(417),
                            Number = 207
                        },
                        new
                        {
                            Id = new Guid("b44bbf84-16be-46bc-adc2-b43eddccc911"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(418),
                            Number = 208
                        },
                        new
                        {
                            Id = new Guid("c45b9087-15d8-4876-934c-9b3ecbf6e34e"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(420),
                            Number = 209
                        },
                        new
                        {
                            Id = new Guid("81aa01a8-4ce2-4e1c-8ced-8da0e341db67"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(421),
                            Number = 210
                        },
                        new
                        {
                            Id = new Guid("d59195d6-38ff-4093-a22c-10bdade5f31a"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(423),
                            Number = 200
                        },
                        new
                        {
                            Id = new Guid("38e47e67-bc22-491b-a6d1-1de1235ad193"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(424),
                            Number = 201
                        },
                        new
                        {
                            Id = new Guid("39f1af94-2ee7-435c-81a9-61529bb5a9a2"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(424),
                            Number = 202
                        },
                        new
                        {
                            Id = new Guid("f88cc98d-f506-441e-a360-b13b675531c6"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(425),
                            Number = 203
                        },
                        new
                        {
                            Id = new Guid("49adc8de-8e22-427f-9a1b-58a4cf466579"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(426),
                            Number = 204
                        },
                        new
                        {
                            Id = new Guid("37a0bfda-8642-4e21-9960-b1471ec4850e"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(427),
                            Number = 205
                        },
                        new
                        {
                            Id = new Guid("6ac3971b-e2d3-486e-a7a6-0c6770a35c64"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(429),
                            Number = 206
                        },
                        new
                        {
                            Id = new Guid("ec44a5e4-3dbd-496a-9d90-7005bc81da3c"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(430),
                            Number = 207
                        },
                        new
                        {
                            Id = new Guid("f1df7d84-5d41-48ce-9416-c8524391c8b5"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(430),
                            Number = 208
                        },
                        new
                        {
                            Id = new Guid("6242103c-3e6a-4761-a6b8-cd19d6c0310e"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(431),
                            Number = 209
                        },
                        new
                        {
                            Id = new Guid("5c3ed446-68fd-4e6c-8c58-4b56140aaee0"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(432),
                            Number = 210
                        },
                        new
                        {
                            Id = new Guid("84fdd8cd-5279-45cf-9174-5fe14eaa91d3"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(433),
                            Number = 200
                        },
                        new
                        {
                            Id = new Guid("c45341bf-f67c-4be7-b566-a7f1e69183d0"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(487),
                            Number = 201
                        },
                        new
                        {
                            Id = new Guid("673016ee-985a-43e3-a2f7-a529d8701d2a"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(488),
                            Number = 202
                        },
                        new
                        {
                            Id = new Guid("ee4eeb71-b986-48bd-889e-b88e59de4ab1"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(490),
                            Number = 203
                        },
                        new
                        {
                            Id = new Guid("84adaf2a-22aa-4022-acd3-07057cae9759"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(491),
                            Number = 204
                        },
                        new
                        {
                            Id = new Guid("b8782bf7-33cc-418d-ad95-ca5cbd62a607"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(491),
                            Number = 205
                        },
                        new
                        {
                            Id = new Guid("692d37bc-4ae5-4f8d-986d-5c83cd0e4c77"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(492),
                            Number = 206
                        },
                        new
                        {
                            Id = new Guid("700e36e5-d31d-4e40-8e97-9692e49483d8"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(493),
                            Number = 207
                        },
                        new
                        {
                            Id = new Guid("69f3e158-644f-470f-8cd5-5e1922e4b251"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(494),
                            Number = 208
                        },
                        new
                        {
                            Id = new Guid("ddee8a4f-9375-490c-ab05-99d9bbc4db86"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(495),
                            Number = 209
                        },
                        new
                        {
                            Id = new Guid("85485f66-be03-402e-bd9f-f6d52ac646af"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(495),
                            Number = 210
                        });
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.Key", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KeyStatus")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("UserId");

                    b.ToTable("Keys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("496b0217-8082-4f75-927a-7652109d6476"),
                            ClassroomId = new Guid("951fca45-f944-413d-9c8c-d05da8013c7d"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(930),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("24439c1f-2dbd-49bc-8a43-92d9abd773fa"),
                            ClassroomId = new Guid("4c401fc0-07ff-4889-9275-ad3bf078b3cc"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(934),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("88acc456-5e82-42d3-92f6-3bc60c44164b"),
                            ClassroomId = new Guid("924c8721-9711-43ec-9c9a-37c5d160bd26"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(935),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("f4b1ef65-5c5a-4102-92b8-ad654e183a5b"),
                            ClassroomId = new Guid("82958cdf-cef8-4ccd-a92f-0053b26df438"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(936),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("3861d315-63aa-48b0-b822-f5195061a754"),
                            ClassroomId = new Guid("e37d358c-0fb7-4781-a4a7-562f8281ed51"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(937),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("34b01c71-efb4-4c75-8557-db8d87719972"),
                            ClassroomId = new Guid("170b317f-4acb-479e-9bff-289ee5d78760"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(939),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("1fcbf1b5-4af1-4c65-a9a6-fab1c3f7b8d1"),
                            ClassroomId = new Guid("816dabe8-50c0-4ee3-af20-3183c21b1da3"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(940),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("81a27c16-20a0-4b71-8e70-1bf0fd69ba84"),
                            ClassroomId = new Guid("c866080c-d5f1-4278-b91f-e6274bff4a1e"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(940),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("1f9c8b10-095c-4ac5-806e-40cc88b4272f"),
                            ClassroomId = new Guid("2b4556ca-b0cf-45a8-b383-c0c001626b57"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(943),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("b97c0172-4652-428e-bc33-9e25edc23da2"),
                            ClassroomId = new Guid("5214f1e1-a2e2-4fe4-8272-c79f73cee851"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(944),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("7bacd4dd-052b-467b-b773-716538f5edaa"),
                            ClassroomId = new Guid("d863b8a5-0b2d-4fec-8266-d843c03b739d"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(945),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("ecec16dc-26b1-4b09-9f47-7828f3b0c57e"),
                            ClassroomId = new Guid("74a6a294-0aba-4f34-a47e-8d8b020c98b0"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(946),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("e23a1715-3588-4304-8d07-021537dca0bc"),
                            ClassroomId = new Guid("ee487369-29ec-4b20-8980-5ec7f1ccda02"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(947),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("9cccf978-3999-43c6-b5b2-b2924e5499d6"),
                            ClassroomId = new Guid("376541c5-23ec-48be-a07c-bfd056662601"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(947),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("023b864c-e8db-4cf6-9665-3c06ba866267"),
                            ClassroomId = new Guid("e6e9483b-88fb-438b-a9f1-687f8583c919"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(948),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("8d71cefe-7cb1-4ea7-9d66-721fa103807b"),
                            ClassroomId = new Guid("fe955a28-3941-41cb-b5eb-3bc36997ae72"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(949),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("1fd0dd07-07ff-4c97-96db-68beacf05f85"),
                            ClassroomId = new Guid("f4f238e0-af3a-45f4-bdd6-ee287c872933"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(951),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("4e4b3789-bbb7-4ae5-9e4c-ca8a0084f3ae"),
                            ClassroomId = new Guid("d7b6a32b-d978-450f-8764-2eefebe2dcc2"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(952),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("66b8b43f-b02f-4b43-835f-6f7707088b96"),
                            ClassroomId = new Guid("ade295fa-7748-49d1-8d0e-d74330d2f601"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(953),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("2ff9dfdc-c0e7-490c-a704-4cebd0776d9d"),
                            ClassroomId = new Guid("cd706952-6977-43e0-8ffc-6507f31b8b43"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(954),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("9a8e6264-698e-480e-8310-8b3f917892bc"),
                            ClassroomId = new Guid("9f1bf1d1-745f-46c7-a49d-105ebe35435d"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(954),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("de09aceb-cb1d-420e-8e86-0bf5fd5fae17"),
                            ClassroomId = new Guid("59c9777e-8d41-4b17-afc0-a91b154b7c3b"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(955),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("7101b7e5-eda2-424f-b830-99558c168e45"),
                            ClassroomId = new Guid("ad3df3b9-ab8b-479c-bdb3-636434ffeb23"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(956),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("61adb17e-f81e-4d55-94aa-a030b1cd8f7d"),
                            ClassroomId = new Guid("9afb391f-f062-4081-8035-43d37934a9b5"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(957),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("d70db168-0802-4bbf-b5ff-e149d826e4d2"),
                            ClassroomId = new Guid("74909e27-be33-4a7a-bff5-414d6a6a76eb"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(959),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("c1a49198-e406-45b9-92af-f207bd0d8827"),
                            ClassroomId = new Guid("59357b4b-0a01-4462-b983-7ba92b2ed339"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(960),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("d9259377-5f9f-45fc-8f25-8c1887a0210e"),
                            ClassroomId = new Guid("3e0c04e1-aee4-4cf3-8dc2-f63f39c5154b"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(960),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("239149e9-2762-42e7-8134-839d930c2500"),
                            ClassroomId = new Guid("96122a4a-3bcd-45e0-9e6f-84d444708c56"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(961),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("c84aa175-f398-400a-9ef8-7f8c5c122f9e"),
                            ClassroomId = new Guid("0fb2adbb-19f4-47df-aacb-f49e82c71a4d"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(962),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("bfdc670c-17a6-4ec5-9e5b-75561ac3d404"),
                            ClassroomId = new Guid("0e266621-c57c-404b-9366-94069bfa4ac7"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(963),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("0f92e6ca-a419-47fd-b752-b800e605f767"),
                            ClassroomId = new Guid("b44bbf84-16be-46bc-adc2-b43eddccc911"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(963),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("3af301a1-2150-450d-94e5-bc807c6a860b"),
                            ClassroomId = new Guid("c45b9087-15d8-4876-934c-9b3ecbf6e34e"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(964),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("9cd521a3-c4ef-449d-beff-09b8591b6d77"),
                            ClassroomId = new Guid("81aa01a8-4ce2-4e1c-8ced-8da0e341db67"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(966),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("8df97dd3-64e8-4e0d-82e8-2290f4c0e36b"),
                            ClassroomId = new Guid("d59195d6-38ff-4093-a22c-10bdade5f31a"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(967),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("b084e253-4229-47a9-9ec0-6d8bd4f105b1"),
                            ClassroomId = new Guid("38e47e67-bc22-491b-a6d1-1de1235ad193"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(968),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("885368c0-0922-429e-83bf-8477e3f41b3d"),
                            ClassroomId = new Guid("39f1af94-2ee7-435c-81a9-61529bb5a9a2"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(969),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("d3fb9727-8ed3-4489-8ed3-a2d12c18417c"),
                            ClassroomId = new Guid("f88cc98d-f506-441e-a360-b13b675531c6"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(969),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("2fc2cb00-84d9-4d3f-a813-be58bff8bb5f"),
                            ClassroomId = new Guid("49adc8de-8e22-427f-9a1b-58a4cf466579"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(970),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("7e97eff2-cf60-4242-840c-f8062bf8c161"),
                            ClassroomId = new Guid("37a0bfda-8642-4e21-9960-b1471ec4850e"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(971),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("7686f21b-32c0-417b-b33a-0668c4b5d47c"),
                            ClassroomId = new Guid("6ac3971b-e2d3-486e-a7a6-0c6770a35c64"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(972),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("1a771e7e-104e-4106-b5e0-e82bc0e8d555"),
                            ClassroomId = new Guid("ec44a5e4-3dbd-496a-9d90-7005bc81da3c"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(975),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("0db4ca7f-a669-4c54-a460-f1d5bde162cc"),
                            ClassroomId = new Guid("f1df7d84-5d41-48ce-9416-c8524391c8b5"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(976),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("07cc0eb1-46a4-406e-b077-fa74bc53a98e"),
                            ClassroomId = new Guid("6242103c-3e6a-4761-a6b8-cd19d6c0310e"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(976),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("d85281c3-5130-4790-84a4-52d84cb163c5"),
                            ClassroomId = new Guid("5c3ed446-68fd-4e6c-8c58-4b56140aaee0"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(977),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("cde88551-a367-4b1f-acea-f519d930bf28"),
                            ClassroomId = new Guid("84fdd8cd-5279-45cf-9174-5fe14eaa91d3"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(978),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("af777de1-2243-44e9-8b1d-92eb6589a6ec"),
                            ClassroomId = new Guid("c45341bf-f67c-4be7-b566-a7f1e69183d0"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(979),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("f2bcb92d-7f93-4bed-a8d4-a029841f86fa"),
                            ClassroomId = new Guid("673016ee-985a-43e3-a2f7-a529d8701d2a"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(980),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("66f62743-a199-42a8-80f6-7cc7891e0628"),
                            ClassroomId = new Guid("ee4eeb71-b986-48bd-889e-b88e59de4ab1"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(980),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("3fe88653-c03b-45a2-acf4-739589355621"),
                            ClassroomId = new Guid("84adaf2a-22aa-4022-acd3-07057cae9759"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(982),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("c35590bc-6d44-463e-b9e6-b2c31c7d1fc6"),
                            ClassroomId = new Guid("b8782bf7-33cc-418d-ad95-ca5cbd62a607"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(983),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("93bb8a47-a311-4cd8-88c6-ebe3dca6e560"),
                            ClassroomId = new Guid("692d37bc-4ae5-4f8d-986d-5c83cd0e4c77"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(984),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("60943ecc-88c0-485f-84d4-75ec76740536"),
                            ClassroomId = new Guid("700e36e5-d31d-4e40-8e97-9692e49483d8"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(985),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("470e20d5-e0bc-42f2-b4e8-32d1a5a7172e"),
                            ClassroomId = new Guid("69f3e158-644f-470f-8cd5-5e1922e4b251"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(986),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("9dadd29e-58b1-489e-82b1-e8754267a6aa"),
                            ClassroomId = new Guid("ddee8a4f-9375-490c-ab05-99d9bbc4db86"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(1010),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("e1e996a1-2d30-4d2e-8f36-17a66bc56687"),
                            ClassroomId = new Guid("85485f66-be03-402e-bd9f-f6d52ac646af"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 55, 67, DateTimeKind.Utc).AddTicks(1011),
                            KeyStatus = 0
                        });
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.KeyRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("EndDateOfRecurrence")
                        .HasColumnType("date");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("UserId");

                    b.ToTable("KeyRequests");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.RegistrationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RegistrationRequests");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<int?>("UserRole")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b8dcb79e-08aa-4597-b84d-44318911c64b"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 54, 583, DateTimeKind.Utc).AddTicks(5593),
                            Email = "admin@gmail.com",
                            FullName = "admin",
                            Gender = 0,
                            Password = "$2a$11$Fmt//G.NL7ctbgYEmdISpucGz/HyfTT7SR3IvqMCacyLvF3bAnGXa",
                            UserRole = 3
                        },
                        new
                        {
                            Id = new Guid("442f41db-b9f4-4355-8389-370b610e97fc"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 54, 701, DateTimeKind.Utc).AddTicks(8245),
                            Email = "dean@gmail.com",
                            FullName = "dean",
                            Gender = 0,
                            Password = "$2a$11$xJh052ek4Y3jdLvm8mSMw.d8q34hQlJekO2PJdIhpNRZ4qJcX24.a",
                            UserRole = 2
                        },
                        new
                        {
                            Id = new Guid("4868443b-1cd4-4874-9d63-a47d9587c4a6"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 54, 820, DateTimeKind.Utc).AddTicks(7122),
                            Email = "teacher@gmail.com",
                            FullName = "teacher",
                            Gender = 0,
                            Password = "$2a$11$M9QDb8lzaIp1K0XZ02hYxuOuOdXQUn9GbmfLYrBZpRaiRH1teKd..",
                            UserRole = 1
                        },
                        new
                        {
                            Id = new Guid("c705f723-15a2-494d-8d88-0955e73f84ea"),
                            CreateTime = new DateTime(2024, 3, 2, 8, 19, 54, 939, DateTimeKind.Utc).AddTicks(8973),
                            Email = "student@gmail.com",
                            FullName = "student",
                            Gender = 0,
                            Password = "$2a$11$hqrUgXCTDNx4qbvUW2pME.b64glnP787NF37143/NZTFbnBW/nUam",
                            UserRole = 0
                        });
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.Key", b =>
                {
                    b.HasOne("ClassroomBooking.Domain.Entities.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassroomBooking.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Classroom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.KeyRequest", b =>
                {
                    b.HasOne("ClassroomBooking.Domain.Entities.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassroomBooking.Domain.Entities.User", "User")
                        .WithMany("Requests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.RegistrationRequest", b =>
                {
                    b.HasOne("ClassroomBooking.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.User", b =>
                {
                    b.Navigation("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
