// <auto-generated />
using System;
using ClassroomBooking.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClassroomBooking.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240219144125_SeedAdmin")]
    partial class SeedAdmin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.Classroom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Building")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Classrooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("588edfb3-0cb0-48b4-a0dc-5e0598b491b5"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9326),
                            Number = 200
                        },
                        new
                        {
                            Id = new Guid("6ffc6264-4408-46aa-a69d-7c6c5d279409"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9357),
                            Number = 201
                        },
                        new
                        {
                            Id = new Guid("e9384fa6-9ce6-4f8d-a7db-ade6a26887f2"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9357),
                            Number = 202
                        },
                        new
                        {
                            Id = new Guid("f8dd4693-9e2b-4143-8e88-6539dc14509c"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9358),
                            Number = 203
                        },
                        new
                        {
                            Id = new Guid("cec28b5a-28d8-49e4-90d6-9194c0c6e90f"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9359),
                            Number = 204
                        },
                        new
                        {
                            Id = new Guid("4422c157-2268-4614-bec7-3eb06e8ea835"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9368),
                            Number = 205
                        },
                        new
                        {
                            Id = new Guid("d9771575-a2ac-4afe-a71f-cf18d227fe26"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9369),
                            Number = 206
                        },
                        new
                        {
                            Id = new Guid("ebba72cb-3417-4e96-ba32-c0f667a9a656"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9370),
                            Number = 207
                        },
                        new
                        {
                            Id = new Guid("6615d6ca-0b6f-42cd-9904-8c3f6f01b62e"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9379),
                            Number = 208
                        },
                        new
                        {
                            Id = new Guid("8cbaf554-6e6a-4763-8f0e-2f51650f5ead"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9381),
                            Number = 209
                        },
                        new
                        {
                            Id = new Guid("5f835056-f460-4d1c-acde-93e43c376fd7"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9382),
                            Number = 210
                        },
                        new
                        {
                            Id = new Guid("e2ade420-6173-401f-8ce4-e68dd28e6cf8"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9382),
                            Number = 200
                        },
                        new
                        {
                            Id = new Guid("ca534d2b-c1f9-4f55-bd2c-e23b5929e658"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9383),
                            Number = 201
                        },
                        new
                        {
                            Id = new Guid("ee0c192c-1c2e-48fc-aeed-04d4e92403bd"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9384),
                            Number = 202
                        },
                        new
                        {
                            Id = new Guid("d315ea6c-f93d-44a2-b3ea-9a43246cd660"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9385),
                            Number = 203
                        },
                        new
                        {
                            Id = new Guid("2c504733-fd3d-45de-96e2-6bf79ace6ab0"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9385),
                            Number = 204
                        },
                        new
                        {
                            Id = new Guid("fcab0f50-79d0-42f5-a8a6-86604280b10b"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9478),
                            Number = 205
                        },
                        new
                        {
                            Id = new Guid("0706152b-8f40-4487-9644-74bfac2f3c7e"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9480),
                            Number = 206
                        },
                        new
                        {
                            Id = new Guid("217b2bcc-cd3e-4733-88ff-736648556b59"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9481),
                            Number = 207
                        },
                        new
                        {
                            Id = new Guid("14f4540a-9ae7-4f1f-a17e-28ca747d3d87"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9482),
                            Number = 208
                        },
                        new
                        {
                            Id = new Guid("ef816ee3-5b45-45a3-85ae-c894f79ce896"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9482),
                            Number = 209
                        },
                        new
                        {
                            Id = new Guid("448330b1-5cb8-4abc-82ab-23119fa46e13"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9483),
                            Number = 210
                        },
                        new
                        {
                            Id = new Guid("a7f3afb7-a6fe-4b0b-85c7-4dc272a27eaf"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9484),
                            Number = 200
                        },
                        new
                        {
                            Id = new Guid("b401ae06-9a6b-481d-97ff-f4d00d8124ae"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9485),
                            Number = 201
                        },
                        new
                        {
                            Id = new Guid("262c6de7-6a39-438b-a6cd-470bdf03a363"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9487),
                            Number = 202
                        },
                        new
                        {
                            Id = new Guid("5338a733-bdd0-44a9-a86b-c5d46c9ec006"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9487),
                            Number = 203
                        },
                        new
                        {
                            Id = new Guid("dc9e8071-0b76-4fa2-948e-5fb0c21bc2a9"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9488),
                            Number = 204
                        },
                        new
                        {
                            Id = new Guid("893ffa55-82c4-4323-9d05-c4e3684fd3ee"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9489),
                            Number = 205
                        },
                        new
                        {
                            Id = new Guid("e1e8ecaf-7ed9-4b74-a9b2-661fef18b00d"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9489),
                            Number = 206
                        },
                        new
                        {
                            Id = new Guid("c20bd1c4-dc24-440e-8b1b-3f268d8b139c"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9490),
                            Number = 207
                        },
                        new
                        {
                            Id = new Guid("36f8ed83-64cb-4208-91a8-c0b5388f5773"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9491),
                            Number = 208
                        },
                        new
                        {
                            Id = new Guid("074117ba-3c66-442d-8f3e-d53c78da3d4d"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9491),
                            Number = 209
                        },
                        new
                        {
                            Id = new Guid("a78488b2-2974-4113-b90f-5846522edd41"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9493),
                            Number = 210
                        },
                        new
                        {
                            Id = new Guid("f2a913b7-d6da-453d-8210-973ef6653c92"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9495),
                            Number = 200
                        },
                        new
                        {
                            Id = new Guid("c6c01ff3-2a87-4fe2-9323-e80884f53d25"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9495),
                            Number = 201
                        },
                        new
                        {
                            Id = new Guid("a24e7308-9e2a-4f82-891e-c45c2a5ac290"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9496),
                            Number = 202
                        },
                        new
                        {
                            Id = new Guid("b676b66a-b3f6-4c2b-87ed-acc040e80fc4"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9497),
                            Number = 203
                        },
                        new
                        {
                            Id = new Guid("b92e9141-d38f-4395-81db-ea3143351538"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9497),
                            Number = 204
                        },
                        new
                        {
                            Id = new Guid("743430dc-6660-44fc-a836-f2adcea82c60"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9498),
                            Number = 205
                        },
                        new
                        {
                            Id = new Guid("340d4580-d5b8-4268-ad73-d89f03866057"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9498),
                            Number = 206
                        },
                        new
                        {
                            Id = new Guid("29bd621d-6d48-4360-8e54-a24a706fa2c3"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9500),
                            Number = 207
                        },
                        new
                        {
                            Id = new Guid("da525018-e4c6-4dbc-b191-19cdc1497af3"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9501),
                            Number = 208
                        },
                        new
                        {
                            Id = new Guid("c97a8717-013f-46a6-a345-9ec70a133da1"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9501),
                            Number = 209
                        },
                        new
                        {
                            Id = new Guid("85b30cf4-d927-420d-8eaa-c86c7fa358ea"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9502),
                            Number = 210
                        },
                        new
                        {
                            Id = new Guid("edb08565-2d91-4720-951c-496ac932dc63"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9503),
                            Number = 200
                        },
                        new
                        {
                            Id = new Guid("23717141-5d1d-439d-b952-5b703be288a9"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9503),
                            Number = 201
                        },
                        new
                        {
                            Id = new Guid("328deb50-509f-493e-b5d6-97aa4d1fadfa"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9504),
                            Number = 202
                        },
                        new
                        {
                            Id = new Guid("12387dc3-072d-4949-942d-17dcf5be684d"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9505),
                            Number = 203
                        },
                        new
                        {
                            Id = new Guid("f41576a5-5216-4b01-913a-72636d3aba9a"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9507),
                            Number = 204
                        },
                        new
                        {
                            Id = new Guid("dafe9b17-213d-400f-978d-064b877a07ff"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9507),
                            Number = 205
                        },
                        new
                        {
                            Id = new Guid("6581b431-1f32-48b1-bf21-774283881f05"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9508),
                            Number = 206
                        },
                        new
                        {
                            Id = new Guid("c50dd343-ca68-4dcb-9aa7-6338c3db2558"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9508),
                            Number = 207
                        },
                        new
                        {
                            Id = new Guid("c7ab1b7d-63e6-4cbc-9754-3e399e5569ec"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9509),
                            Number = 208
                        },
                        new
                        {
                            Id = new Guid("998cf491-a183-45fb-b4bb-d06aff141b1d"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9510),
                            Number = 209
                        },
                        new
                        {
                            Id = new Guid("d8ad591d-96f0-4b50-9ff0-4ee43cfcb2e5"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9510),
                            Number = 210
                        });
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.Key", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KeyStatus")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("UserId");

                    b.ToTable("Keys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5eefba10-d68b-4d1b-8e23-c1bd8147a358"),
                            ClassroomId = new Guid("588edfb3-0cb0-48b4-a0dc-5e0598b491b5"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9816),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("7b736cf3-270a-4207-aa07-fba630dd61bf"),
                            ClassroomId = new Guid("6ffc6264-4408-46aa-a69d-7c6c5d279409"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9823),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("be387ea1-1dc4-4e6b-8dfd-ad069c0777fc"),
                            ClassroomId = new Guid("e9384fa6-9ce6-4f8d-a7db-ade6a26887f2"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9825),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("0cb9d5a1-040c-4b23-b659-189e538a3a7d"),
                            ClassroomId = new Guid("f8dd4693-9e2b-4143-8e88-6539dc14509c"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9826),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("1e382d65-cc70-45d3-b757-d6b8395bba16"),
                            ClassroomId = new Guid("cec28b5a-28d8-49e4-90d6-9194c0c6e90f"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9827),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("437a5648-496e-43be-bd17-94a8d35ea86d"),
                            ClassroomId = new Guid("4422c157-2268-4614-bec7-3eb06e8ea835"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9828),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("d6aa3cf3-a5c9-4da8-b1cb-f8a252ae2a39"),
                            ClassroomId = new Guid("d9771575-a2ac-4afe-a71f-cf18d227fe26"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9829),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("adf91e68-d318-4853-9aea-d0a1b9aac7ef"),
                            ClassroomId = new Guid("ebba72cb-3417-4e96-ba32-c0f667a9a656"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9830),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("c2db19db-7de3-4732-b980-8ac93a9cbeb9"),
                            ClassroomId = new Guid("6615d6ca-0b6f-42cd-9904-8c3f6f01b62e"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9831),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("c50b3de8-df1a-493d-aded-1ca4aaa9ffe1"),
                            ClassroomId = new Guid("8cbaf554-6e6a-4763-8f0e-2f51650f5ead"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9833),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("ea5971a5-e3aa-4141-b512-cfa62b4df0ca"),
                            ClassroomId = new Guid("5f835056-f460-4d1c-acde-93e43c376fd7"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9834),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("e046ba06-69fd-4596-9014-5585ce585bad"),
                            ClassroomId = new Guid("e2ade420-6173-401f-8ce4-e68dd28e6cf8"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9835),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("ac354aa4-1713-4ce4-8ffb-238d0bf8b574"),
                            ClassroomId = new Guid("ca534d2b-c1f9-4f55-bd2c-e23b5929e658"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9835),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("7d5b5ede-ea78-4f8d-ab87-adbfba27b825"),
                            ClassroomId = new Guid("ee0c192c-1c2e-48fc-aeed-04d4e92403bd"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9836),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("90cf1c67-0d43-484d-b7b2-d5db38af4bdc"),
                            ClassroomId = new Guid("d315ea6c-f93d-44a2-b3ea-9a43246cd660"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9837),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("fe432006-cb93-4960-b83c-03c8defdfc52"),
                            ClassroomId = new Guid("2c504733-fd3d-45de-96e2-6bf79ace6ab0"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9837),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("77f7e9cf-de0f-4332-807d-543500ea354d"),
                            ClassroomId = new Guid("fcab0f50-79d0-42f5-a8a6-86604280b10b"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9838),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("df1ca710-df84-4b31-9b1c-fe10a80e8332"),
                            ClassroomId = new Guid("0706152b-8f40-4487-9644-74bfac2f3c7e"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9841),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("6337d6a4-c0ee-4231-8c81-88f1173ded8b"),
                            ClassroomId = new Guid("217b2bcc-cd3e-4733-88ff-736648556b59"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9841),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("e2da85d9-178e-4a04-839f-cf972414d5a9"),
                            ClassroomId = new Guid("14f4540a-9ae7-4f1f-a17e-28ca747d3d87"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9842),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("61a6e1f9-5cd3-4da2-806d-5e8f5ac7ad25"),
                            ClassroomId = new Guid("ef816ee3-5b45-45a3-85ae-c894f79ce896"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9843),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("677b7e1f-99f4-4cbf-a933-0f155209a1ad"),
                            ClassroomId = new Guid("448330b1-5cb8-4abc-82ab-23119fa46e13"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9843),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("82b26822-6fa6-45a5-80b5-4b5cbfcea318"),
                            ClassroomId = new Guid("a7f3afb7-a6fe-4b0b-85c7-4dc272a27eaf"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9844),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("e463dca6-ba08-492a-8e54-8b77405b70df"),
                            ClassroomId = new Guid("b401ae06-9a6b-481d-97ff-f4d00d8124ae"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9845),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("f200b549-171e-4fe2-9bbe-f3f638f03744"),
                            ClassroomId = new Guid("262c6de7-6a39-438b-a6cd-470bdf03a363"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9845),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("84a002b1-de79-4e91-9cbe-e52c70d9bde0"),
                            ClassroomId = new Guid("5338a733-bdd0-44a9-a86b-c5d46c9ec006"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9847),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("592f8656-502a-4c41-a193-b8ce396f6ea5"),
                            ClassroomId = new Guid("dc9e8071-0b76-4fa2-948e-5fb0c21bc2a9"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9848),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("047bf56a-88e3-42c4-a02d-52ccd7384c86"),
                            ClassroomId = new Guid("893ffa55-82c4-4323-9d05-c4e3684fd3ee"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9849),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("b902b157-c4e8-43fa-a8ea-02bdc6cdcdf1"),
                            ClassroomId = new Guid("e1e8ecaf-7ed9-4b74-a9b2-661fef18b00d"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9849),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("1738f6b9-34c1-4c20-be3d-5dddfe2cf466"),
                            ClassroomId = new Guid("c20bd1c4-dc24-440e-8b1b-3f268d8b139c"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9850),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("fd204e70-e45f-4537-b3c9-152c76ecb39d"),
                            ClassroomId = new Guid("36f8ed83-64cb-4208-91a8-c0b5388f5773"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9851),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("263f7cad-9f13-4559-944d-4671cee3dd62"),
                            ClassroomId = new Guid("074117ba-3c66-442d-8f3e-d53c78da3d4d"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9851),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("a01266c5-fc15-44c1-a4be-713caaa72224"),
                            ClassroomId = new Guid("a78488b2-2974-4113-b90f-5846522edd41"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9852),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("5313e984-e047-4d13-9b7f-498714f8d272"),
                            ClassroomId = new Guid("f2a913b7-d6da-453d-8210-973ef6653c92"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9930),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("ecdd1c70-0f05-4ab1-8a27-f2baa6945388"),
                            ClassroomId = new Guid("c6c01ff3-2a87-4fe2-9323-e80884f53d25"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9931),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("fc8cfe1a-0610-4693-9d6f-4c7daab8116a"),
                            ClassroomId = new Guid("a24e7308-9e2a-4f82-891e-c45c2a5ac290"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9933),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("38e4894a-6ff4-40c8-823b-bc843c6e7f4b"),
                            ClassroomId = new Guid("b676b66a-b3f6-4c2b-87ed-acc040e80fc4"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9934),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("3592434a-3831-4d49-b17a-4bf78d6fcf73"),
                            ClassroomId = new Guid("b92e9141-d38f-4395-81db-ea3143351538"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9935),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("255e7057-7dac-4a4d-aee5-bfb5d5569888"),
                            ClassroomId = new Guid("743430dc-6660-44fc-a836-f2adcea82c60"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9936),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("800bbba7-e56e-4e7d-a624-131b8652f178"),
                            ClassroomId = new Guid("340d4580-d5b8-4268-ad73-d89f03866057"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9937),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("a0fdcd1f-6698-4132-889a-e6487086ab10"),
                            ClassroomId = new Guid("29bd621d-6d48-4360-8e54-a24a706fa2c3"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9938),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("7de84211-ea21-4776-b349-8adacf49969b"),
                            ClassroomId = new Guid("da525018-e4c6-4dbc-b191-19cdc1497af3"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9941),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("abbe0140-5f06-4894-9f3c-1bf3857f3444"),
                            ClassroomId = new Guid("c97a8717-013f-46a6-a345-9ec70a133da1"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9942),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("5f6566a9-8af8-43be-abf6-b55adb190ce4"),
                            ClassroomId = new Guid("85b30cf4-d927-420d-8eaa-c86c7fa358ea"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9943),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("c4364924-b9ed-41c0-96fd-55509c2d48aa"),
                            ClassroomId = new Guid("edb08565-2d91-4720-951c-496ac932dc63"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9944),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("536ac7b1-d33b-4317-87a1-1d9154a43426"),
                            ClassroomId = new Guid("23717141-5d1d-439d-b952-5b703be288a9"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9945),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("115b9c9a-cc84-40cd-8605-c603c234f432"),
                            ClassroomId = new Guid("328deb50-509f-493e-b5d6-97aa4d1fadfa"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9946),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("1c11be73-485e-4852-a01f-e96b7a71c577"),
                            ClassroomId = new Guid("12387dc3-072d-4949-942d-17dcf5be684d"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9947),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("79d6e93c-67bf-4e20-93ea-67c61dc28957"),
                            ClassroomId = new Guid("f41576a5-5216-4b01-913a-72636d3aba9a"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9948),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("d1e406a7-0b0d-4d89-a554-9dae5b548855"),
                            ClassroomId = new Guid("dafe9b17-213d-400f-978d-064b877a07ff"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9950),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("3fc36493-9619-4bbd-aa54-18268d84d700"),
                            ClassroomId = new Guid("6581b431-1f32-48b1-bf21-774283881f05"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9951),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("f1f20d11-ec6f-4e38-8c9f-2e83ccad5379"),
                            ClassroomId = new Guid("c50dd343-ca68-4dcb-9aa7-6338c3db2558"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9952),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("5bf68691-85be-4de4-b7f0-e2cb4c019110"),
                            ClassroomId = new Guid("c7ab1b7d-63e6-4cbc-9754-3e399e5569ec"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9953),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("0c3a6961-3ee6-424e-be32-6fe88faa2c0d"),
                            ClassroomId = new Guid("998cf491-a183-45fb-b4bb-d06aff141b1d"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9954),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("cc023f9a-cadc-4c7c-8b11-3fce17f6a4f1"),
                            ClassroomId = new Guid("d8ad591d-96f0-4b50-9ff0-4ee43cfcb2e5"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 25, 59, DateTimeKind.Utc).AddTicks(9955),
                            KeyStatus = 0
                        });
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.KeyRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("UserId");

                    b.ToTable("KeyRequests");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.RegistrationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RegistrationRequests");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<int?>("UserRole")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2a49ee4e-cfd9-4ea9-8012-cbf9ad0a8d9c"),
                            CreateTime = new DateTime(2024, 2, 19, 14, 41, 24, 880, DateTimeKind.Utc).AddTicks(7079),
                            Email = "admin@gmail.com",
                            FullName = "admin",
                            Gender = 0,
                            Password = "$2a$11$SotczS9swgEC.JY6WwIn.u28JDAb2QPmv6GUraS4g4ev2DesFh0Su",
                            UserRole = 3
                        });
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.Key", b =>
                {
                    b.HasOne("ClassroomBooking.Domain.Entities.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassroomBooking.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Classroom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.KeyRequest", b =>
                {
                    b.HasOne("ClassroomBooking.Domain.Entities.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassroomBooking.Domain.Entities.User", "User")
                        .WithMany("Requests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.RegistrationRequest", b =>
                {
                    b.HasOne("ClassroomBooking.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.User", b =>
                {
                    b.Navigation("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
