// <auto-generated />
using System;
using ClassroomBooking.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClassroomBooking.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240221062435_AddTestUsers")]
    partial class AddTestUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.Classroom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Building")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Classrooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2a5bf3cc-a18e-4a0b-bb6a-b9fe777c00f8"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7340),
                            Number = 200
                        },
                        new
                        {
                            Id = new Guid("8e2cb16b-12ef-4bf5-999f-c7a406072701"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7360),
                            Number = 201
                        },
                        new
                        {
                            Id = new Guid("95eef5f9-a8ca-4c3f-b279-e40b84eec613"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7360),
                            Number = 202
                        },
                        new
                        {
                            Id = new Guid("47374e5c-7d9f-4f00-b241-875ad91c86c9"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7360),
                            Number = 203
                        },
                        new
                        {
                            Id = new Guid("a13b536c-f2e5-44c0-9e0a-329f7a6c4c1a"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7370),
                            Number = 204
                        },
                        new
                        {
                            Id = new Guid("2275a065-8c8e-4062-acc9-a22664cffc26"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7380),
                            Number = 205
                        },
                        new
                        {
                            Id = new Guid("95d506a5-c587-4efb-851f-e7ea1f68abde"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7380),
                            Number = 206
                        },
                        new
                        {
                            Id = new Guid("3f84beaf-fce6-4ec8-ba02-2855faa683ec"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7380),
                            Number = 207
                        },
                        new
                        {
                            Id = new Guid("2eb2854a-6e96-4cce-8baf-7a5d87d8bf81"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7380),
                            Number = 208
                        },
                        new
                        {
                            Id = new Guid("0f82d7c3-f6a9-4410-b4ca-965bdb400233"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7390),
                            Number = 209
                        },
                        new
                        {
                            Id = new Guid("6598dc4d-2a50-4e87-a175-cc1fe6f3e42f"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7390),
                            Number = 210
                        },
                        new
                        {
                            Id = new Guid("1183bb8e-3231-478b-b454-24d18ed645f6"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7390),
                            Number = 200
                        },
                        new
                        {
                            Id = new Guid("8fd68027-d0f2-4357-9498-27dd912d7764"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7390),
                            Number = 201
                        },
                        new
                        {
                            Id = new Guid("7d1d2a14-225d-432e-a14a-ec4397735827"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7400),
                            Number = 202
                        },
                        new
                        {
                            Id = new Guid("cb1e4545-b01d-4e5c-927b-64c5d70785ef"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7400),
                            Number = 203
                        },
                        new
                        {
                            Id = new Guid("93469dbf-7d66-4d74-be18-acd77c646e24"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7400),
                            Number = 204
                        },
                        new
                        {
                            Id = new Guid("85fe70d1-2e7d-47d5-a1fa-141f0b0541d1"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7400),
                            Number = 205
                        },
                        new
                        {
                            Id = new Guid("ae415247-7615-4ce6-81c6-d9994cfe536f"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7410),
                            Number = 206
                        },
                        new
                        {
                            Id = new Guid("82085a31-00ab-4a7f-b040-c1d32bcbf639"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7410),
                            Number = 207
                        },
                        new
                        {
                            Id = new Guid("48d17650-8068-4f23-a3f1-246504426aba"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7410),
                            Number = 208
                        },
                        new
                        {
                            Id = new Guid("a354b2b1-881c-4fef-8b45-c2a264f1a489"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7410),
                            Number = 209
                        },
                        new
                        {
                            Id = new Guid("7e19fea7-6ae3-4492-b778-ad36638acbe0"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7420),
                            Number = 210
                        },
                        new
                        {
                            Id = new Guid("18a9fccb-e4ff-45ee-8aad-7a718254989b"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7450),
                            Number = 200
                        },
                        new
                        {
                            Id = new Guid("ff8724d0-35c5-4dda-9202-45c9371e26f5"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7460),
                            Number = 201
                        },
                        new
                        {
                            Id = new Guid("f75b3ce1-1168-411c-8d0c-e749a7c9d552"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7460),
                            Number = 202
                        },
                        new
                        {
                            Id = new Guid("d2d88ef5-f619-4b98-800c-a3438d90ff7d"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7460),
                            Number = 203
                        },
                        new
                        {
                            Id = new Guid("b11deeca-1007-4799-b640-dbca9e00360e"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7500),
                            Number = 204
                        },
                        new
                        {
                            Id = new Guid("ea96e44a-77a7-4dee-a005-9c89d4983fe3"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7500),
                            Number = 205
                        },
                        new
                        {
                            Id = new Guid("c6ed9943-d11b-4b58-8320-039b4ad960e4"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7510),
                            Number = 206
                        },
                        new
                        {
                            Id = new Guid("fbf7d426-ef1b-4415-a371-e1f1e16d6841"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7510),
                            Number = 207
                        },
                        new
                        {
                            Id = new Guid("b22ac21e-d74a-4e4d-9d66-ebe5c26c10ac"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7510),
                            Number = 208
                        },
                        new
                        {
                            Id = new Guid("31d76c89-a9ca-4082-8650-534a46caa425"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7520),
                            Number = 209
                        },
                        new
                        {
                            Id = new Guid("8830e76e-4c53-45c2-8c41-334156d1c7fd"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7520),
                            Number = 210
                        },
                        new
                        {
                            Id = new Guid("a8a07254-8278-46f9-801e-b4950d995c65"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7520),
                            Number = 200
                        },
                        new
                        {
                            Id = new Guid("479d357e-6d46-4ea1-8373-38de8bc5b39d"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7530),
                            Number = 201
                        },
                        new
                        {
                            Id = new Guid("c6cb72f0-3bc4-4f62-b1e6-87013db0dfae"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7530),
                            Number = 202
                        },
                        new
                        {
                            Id = new Guid("e4989a15-e7a5-4102-9355-50c48a1a525f"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7530),
                            Number = 203
                        },
                        new
                        {
                            Id = new Guid("f8a93f11-8e4b-4a69-b2bd-ffdd56676788"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7530),
                            Number = 204
                        },
                        new
                        {
                            Id = new Guid("6d234744-b4f4-4254-bdb9-d633201a8196"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7540),
                            Number = 205
                        },
                        new
                        {
                            Id = new Guid("7a6ecafe-52c6-41c1-a080-916e7d409902"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7540),
                            Number = 206
                        },
                        new
                        {
                            Id = new Guid("680791cf-3234-45bc-9c57-6ac3d246e1d1"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7540),
                            Number = 207
                        },
                        new
                        {
                            Id = new Guid("54490943-f319-44ef-85fb-fd0b6dbcd2eb"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7550),
                            Number = 208
                        },
                        new
                        {
                            Id = new Guid("0c4706b8-cf36-4faa-8445-06b84ed3430a"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7550),
                            Number = 209
                        },
                        new
                        {
                            Id = new Guid("f5f54f70-3309-4e87-872f-6425f3eb6b4b"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7550),
                            Number = 210
                        },
                        new
                        {
                            Id = new Guid("c4153f18-b008-4a85-85ad-7ebced303b84"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7550),
                            Number = 200
                        },
                        new
                        {
                            Id = new Guid("dec9171b-5e05-4a05-aa28-37f6b01fcefb"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7560),
                            Number = 201
                        },
                        new
                        {
                            Id = new Guid("8ba413f7-0af6-4800-8db2-2eb29946b524"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7560),
                            Number = 202
                        },
                        new
                        {
                            Id = new Guid("acea1526-6dc1-468f-99de-d4c7daa46a8c"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7560),
                            Number = 203
                        },
                        new
                        {
                            Id = new Guid("652aef9a-f9d4-4ab7-a5d1-7db1f06d5c5a"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7560),
                            Number = 204
                        },
                        new
                        {
                            Id = new Guid("44a83e72-b567-4b9d-8587-720fe4d73d7a"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7570),
                            Number = 205
                        },
                        new
                        {
                            Id = new Guid("98cabc13-f4ff-4bd8-9ca9-6b6b13ffcf47"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7570),
                            Number = 206
                        },
                        new
                        {
                            Id = new Guid("4bc10cc4-518e-455f-aa4f-4ff404f9e38b"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7570),
                            Number = 207
                        },
                        new
                        {
                            Id = new Guid("2f5c24b5-b71f-4151-9d22-257388f210cb"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7570),
                            Number = 208
                        },
                        new
                        {
                            Id = new Guid("ea12d488-5d72-4549-8a53-08f9aa9a96d6"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7570),
                            Number = 209
                        },
                        new
                        {
                            Id = new Guid("12671aa0-1366-4e58-aba9-d3d63f90cefc"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(7580),
                            Number = 210
                        });
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.Key", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KeyStatus")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("UserId");

                    b.ToTable("Keys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2986a5f7-0edb-4ec8-880d-0db970bc5d1a"),
                            ClassroomId = new Guid("2a5bf3cc-a18e-4a0b-bb6a-b9fe777c00f8"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8130),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("bf3d1794-582c-4ab8-89e2-b4a81d8f4881"),
                            ClassroomId = new Guid("8e2cb16b-12ef-4bf5-999f-c7a406072701"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8140),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("ffb65107-7b4c-43ae-a7e8-023249e42bdf"),
                            ClassroomId = new Guid("95eef5f9-a8ca-4c3f-b279-e40b84eec613"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8140),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("abf30d1a-efb6-4f16-85eb-2ac56b6a95b4"),
                            ClassroomId = new Guid("47374e5c-7d9f-4f00-b241-875ad91c86c9"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8140),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("1d8b177e-73c5-489b-8e1c-c314238bf269"),
                            ClassroomId = new Guid("a13b536c-f2e5-44c0-9e0a-329f7a6c4c1a"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8150),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("21da6501-b9ed-487b-a4ed-0d867d69d019"),
                            ClassroomId = new Guid("2275a065-8c8e-4062-acc9-a22664cffc26"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8150),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("dc1191d2-20b2-4649-b7c8-30f2dbb16200"),
                            ClassroomId = new Guid("95d506a5-c587-4efb-851f-e7ea1f68abde"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8150),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("e87c982c-a488-4dc2-978a-c335847fe310"),
                            ClassroomId = new Guid("3f84beaf-fce6-4ec8-ba02-2855faa683ec"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8150),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("2cac52b1-8cf2-4825-8913-3e5de5958487"),
                            ClassroomId = new Guid("2eb2854a-6e96-4cce-8baf-7a5d87d8bf81"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8160),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("ac90b01c-5218-4660-af81-723cb240b3c3"),
                            ClassroomId = new Guid("0f82d7c3-f6a9-4410-b4ca-965bdb400233"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8160),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("1d0ff5e1-a2b1-492c-b7ed-2cb25526b5f9"),
                            ClassroomId = new Guid("6598dc4d-2a50-4e87-a175-cc1fe6f3e42f"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8160),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("bf8c4134-d8f9-4310-982a-fd3d7bd724d2"),
                            ClassroomId = new Guid("1183bb8e-3231-478b-b454-24d18ed645f6"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8160),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("f6b06240-a6dd-4583-9dd4-9d610cc51f99"),
                            ClassroomId = new Guid("8fd68027-d0f2-4357-9498-27dd912d7764"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8170),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("616ef89a-0775-451a-85d6-bcbe8ac6403c"),
                            ClassroomId = new Guid("7d1d2a14-225d-432e-a14a-ec4397735827"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8170),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("1d034c01-33f2-4bbb-9121-e5d869bbbcbb"),
                            ClassroomId = new Guid("cb1e4545-b01d-4e5c-927b-64c5d70785ef"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8170),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("3ebd2ed7-4338-437f-a74a-376bd1e0ad44"),
                            ClassroomId = new Guid("93469dbf-7d66-4d74-be18-acd77c646e24"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8170),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("b33e8873-b01e-4f25-a182-63e1e446527b"),
                            ClassroomId = new Guid("85fe70d1-2e7d-47d5-a1fa-141f0b0541d1"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8180),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("ec054cdb-70d2-482b-826c-f6bdf491584e"),
                            ClassroomId = new Guid("ae415247-7615-4ce6-81c6-d9994cfe536f"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8180),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("973d0608-7ce9-4b0a-8cdb-9e1872000eee"),
                            ClassroomId = new Guid("82085a31-00ab-4a7f-b040-c1d32bcbf639"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8180),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("5a2dd956-e2be-4482-8271-e2bf8477378c"),
                            ClassroomId = new Guid("48d17650-8068-4f23-a3f1-246504426aba"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8180),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("0fbfb7dc-11d8-4159-b098-810ed34bb6ba"),
                            ClassroomId = new Guid("a354b2b1-881c-4fef-8b45-c2a264f1a489"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8190),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("3fb6d728-8ae8-44d1-a625-8054a4d22a91"),
                            ClassroomId = new Guid("7e19fea7-6ae3-4492-b778-ad36638acbe0"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8190),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("7d14ae64-0e2d-4ff5-8a41-4f50976c15aa"),
                            ClassroomId = new Guid("18a9fccb-e4ff-45ee-8aad-7a718254989b"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8190),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("90673070-4c1c-4ffb-b18b-002ba69931a4"),
                            ClassroomId = new Guid("ff8724d0-35c5-4dda-9202-45c9371e26f5"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8260),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("45340f58-3344-44ba-9929-8fe9fae6dcbd"),
                            ClassroomId = new Guid("f75b3ce1-1168-411c-8d0c-e749a7c9d552"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8270),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("7fb2e4a0-b92e-46d6-abc2-a1f657c26a0d"),
                            ClassroomId = new Guid("d2d88ef5-f619-4b98-800c-a3438d90ff7d"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8270),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("7888bb25-91d4-48fc-aa9b-a644fdf9b56b"),
                            ClassroomId = new Guid("b11deeca-1007-4799-b640-dbca9e00360e"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8270),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("a138eeb2-9341-4698-8a1b-a2fb8950ca8f"),
                            ClassroomId = new Guid("ea96e44a-77a7-4dee-a005-9c89d4983fe3"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8270),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("ca2e47a6-a13b-4798-a7e3-d8d5433bf185"),
                            ClassroomId = new Guid("c6ed9943-d11b-4b58-8320-039b4ad960e4"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8280),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("8dfa0d83-b030-4bc5-809c-0b8bea132d77"),
                            ClassroomId = new Guid("fbf7d426-ef1b-4415-a371-e1f1e16d6841"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8280),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("0b71719d-70d4-4f60-9250-7f1af14cf0f6"),
                            ClassroomId = new Guid("b22ac21e-d74a-4e4d-9d66-ebe5c26c10ac"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8280),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("a4b3285c-32e5-4453-b616-0dce470af914"),
                            ClassroomId = new Guid("31d76c89-a9ca-4082-8650-534a46caa425"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8280),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("f9c3216f-db23-4308-834e-067370cefe41"),
                            ClassroomId = new Guid("8830e76e-4c53-45c2-8c41-334156d1c7fd"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8280),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("30461ccd-4509-46a9-b5a6-6d9af77a8f41"),
                            ClassroomId = new Guid("a8a07254-8278-46f9-801e-b4950d995c65"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8290),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("85afc83f-4c4d-458d-bd64-8e3b6d5178c9"),
                            ClassroomId = new Guid("479d357e-6d46-4ea1-8373-38de8bc5b39d"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8290),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("67202716-c266-4689-82da-51ce5a508fac"),
                            ClassroomId = new Guid("c6cb72f0-3bc4-4f62-b1e6-87013db0dfae"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8290),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("b6dbc45f-cda8-43db-8c2d-4ef6e3bc33ae"),
                            ClassroomId = new Guid("e4989a15-e7a5-4102-9355-50c48a1a525f"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8290),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("a7c6e11a-374e-4013-9d32-d14ca5c9fce7"),
                            ClassroomId = new Guid("f8a93f11-8e4b-4a69-b2bd-ffdd56676788"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8300),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("533af30f-b404-40c3-9443-7c88c7e74892"),
                            ClassroomId = new Guid("6d234744-b4f4-4254-bdb9-d633201a8196"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8300),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("26fae369-b7d4-4c60-9a6c-3fd4bb4cc1ff"),
                            ClassroomId = new Guid("7a6ecafe-52c6-41c1-a080-916e7d409902"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8300),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("5546075b-9afc-4b08-b0cf-4688eafd61f9"),
                            ClassroomId = new Guid("680791cf-3234-45bc-9c57-6ac3d246e1d1"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8300),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("6b97de1b-1daf-4179-b47d-c793c9920558"),
                            ClassroomId = new Guid("54490943-f319-44ef-85fb-fd0b6dbcd2eb"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8310),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("4a22325f-ac98-4e19-8e92-7c4db73cacb6"),
                            ClassroomId = new Guid("0c4706b8-cf36-4faa-8445-06b84ed3430a"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8310),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("eeff3576-1f02-4e2d-ab40-f7bd4bdd43ac"),
                            ClassroomId = new Guid("f5f54f70-3309-4e87-872f-6425f3eb6b4b"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8310),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("abd8a7ca-84a4-4c4a-98f8-9c9549549fa3"),
                            ClassroomId = new Guid("c4153f18-b008-4a85-85ad-7ebced303b84"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8310),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("6fb47eff-3775-420d-af43-99ad200b1575"),
                            ClassroomId = new Guid("dec9171b-5e05-4a05-aa28-37f6b01fcefb"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8320),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("2580d215-6c53-49ce-88a5-6a0bd13fdb3e"),
                            ClassroomId = new Guid("8ba413f7-0af6-4800-8db2-2eb29946b524"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8320),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("d9e224b3-41ad-46f5-9d1f-557c63c1f2ce"),
                            ClassroomId = new Guid("acea1526-6dc1-468f-99de-d4c7daa46a8c"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8320),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("45cd7318-4109-4a9b-b808-7899e7aa9f46"),
                            ClassroomId = new Guid("652aef9a-f9d4-4ab7-a5d1-7db1f06d5c5a"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8320),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("cd015ea9-be25-4a8b-b5d9-315c0e8cd7ee"),
                            ClassroomId = new Guid("44a83e72-b567-4b9d-8587-720fe4d73d7a"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8330),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("37ffb39f-9299-4d78-bfc7-b059f2358a0b"),
                            ClassroomId = new Guid("98cabc13-f4ff-4bd8-9ca9-6b6b13ffcf47"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8330),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("e2d625b9-1403-4f2f-b868-90b66626aaa0"),
                            ClassroomId = new Guid("4bc10cc4-518e-455f-aa4f-4ff404f9e38b"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8330),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("c83dd9ee-af5f-41f6-962b-ad6da4480a97"),
                            ClassroomId = new Guid("2f5c24b5-b71f-4151-9d22-257388f210cb"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8330),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("aa56f141-af96-4b2c-8a3f-4e578b05e0b6"),
                            ClassroomId = new Guid("ea12d488-5d72-4549-8a53-08f9aa9a96d6"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8340),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("e8e4b0dd-9298-4897-9bec-37907ca813c7"),
                            ClassroomId = new Guid("12671aa0-1366-4e58-aba9-d3d63f90cefc"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 35, 65, DateTimeKind.Utc).AddTicks(8340),
                            KeyStatus = 0
                        });
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.KeyRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("UserId");

                    b.ToTable("KeyRequests");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.RegistrationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RegistrationRequests");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<int?>("UserRole")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("505dbb55-c9fe-4cc7-90e2-dc835a531a65"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 34, 617, DateTimeKind.Utc).AddTicks(3310),
                            Email = "admin@gmail.com",
                            FullName = "admin",
                            Gender = 0,
                            Password = "$2a$11$.qMEV3uEB33tzwrMOIlcR.E1Pmuj/Jt8roV4ZOx/x034NPx1FrrGC",
                            UserRole = 3
                        },
                        new
                        {
                            Id = new Guid("03cbb024-1302-4bbf-9c29-d3f95449dd64"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 34, 729, DateTimeKind.Utc).AddTicks(4560),
                            Email = "dean@gmail.com",
                            FullName = "dean",
                            Gender = 0,
                            Password = "$2a$11$OVq6tQsqJHwCbr5OrW/6DO6/TDdjLlMa99FRzxml5iNsr3QFIQnNW",
                            UserRole = 2
                        },
                        new
                        {
                            Id = new Guid("69620c2e-db3e-4c0e-838b-e886e52777ac"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 34, 843, DateTimeKind.Utc).AddTicks(4600),
                            Email = "teacher@gmail.com",
                            FullName = "teacher",
                            Gender = 0,
                            Password = "$2a$11$RDgQ6wGSlovS9VOXUc1lD.Pqis9shvgiZJE.H/zVDlbPzgKh9ejGa",
                            UserRole = 1
                        },
                        new
                        {
                            Id = new Guid("b264600f-f2fb-43a2-a74f-fdf4c88bc322"),
                            CreateTime = new DateTime(2024, 2, 21, 6, 24, 34, 955, DateTimeKind.Utc).AddTicks(3420),
                            Email = "student@gmail.com",
                            FullName = "student",
                            Gender = 0,
                            Password = "$2a$11$Ky0HdKNBUHju8TlwV6JI7eepCQOobljzYDPTO0kHiZNmIGodq1AwC",
                            UserRole = 0
                        });
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.Key", b =>
                {
                    b.HasOne("ClassroomBooking.Domain.Entities.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassroomBooking.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Classroom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.KeyRequest", b =>
                {
                    b.HasOne("ClassroomBooking.Domain.Entities.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassroomBooking.Domain.Entities.User", "User")
                        .WithMany("Requests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.RegistrationRequest", b =>
                {
                    b.HasOne("ClassroomBooking.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.User", b =>
                {
                    b.Navigation("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
