// <auto-generated />
using System;
using ClassroomBooking.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClassroomBooking.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240310035734_AddTransferKeyRequest")]
    partial class AddTransferKeyRequest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.Classroom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Building")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Classrooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("029da668-f86f-4a64-8d8a-75cbd02423d8"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 588, DateTimeKind.Utc).AddTicks(9860),
                            Number = 200
                        },
                        new
                        {
                            Id = new Guid("0f821ebe-5456-466c-b394-e28b21c5ebe6"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 588, DateTimeKind.Utc).AddTicks(9920),
                            Number = 201
                        },
                        new
                        {
                            Id = new Guid("fac3a3e8-b15c-40e0-a871-3d0f7e5f94b3"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 588, DateTimeKind.Utc).AddTicks(9920),
                            Number = 202
                        },
                        new
                        {
                            Id = new Guid("2897600a-13e1-4b98-9a8b-43659909b1b3"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 588, DateTimeKind.Utc).AddTicks(9920),
                            Number = 203
                        },
                        new
                        {
                            Id = new Guid("0e195743-b407-4155-a25b-38cbf726985b"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 588, DateTimeKind.Utc).AddTicks(9930),
                            Number = 204
                        },
                        new
                        {
                            Id = new Guid("854e9792-2c57-4707-8be4-398dece1c835"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 588, DateTimeKind.Utc).AddTicks(9930),
                            Number = 205
                        },
                        new
                        {
                            Id = new Guid("6597fc3b-4b6b-4ef1-94bc-63699d7f1f79"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 588, DateTimeKind.Utc).AddTicks(9940),
                            Number = 206
                        },
                        new
                        {
                            Id = new Guid("561e6743-fef8-42ca-84d6-c71a1d35f227"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 588, DateTimeKind.Utc).AddTicks(9940),
                            Number = 207
                        },
                        new
                        {
                            Id = new Guid("c63e6bd0-e712-48e5-86ad-364a46a9cf95"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 588, DateTimeKind.Utc).AddTicks(9940),
                            Number = 208
                        },
                        new
                        {
                            Id = new Guid("aed7f9e3-a88c-481e-884c-41059113f307"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 588, DateTimeKind.Utc).AddTicks(9940),
                            Number = 209
                        },
                        new
                        {
                            Id = new Guid("645daf2c-0788-465a-98f2-443ced657d4b"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 588, DateTimeKind.Utc).AddTicks(9950),
                            Number = 210
                        },
                        new
                        {
                            Id = new Guid("66149d1f-9f3e-4bbd-9ac6-743d7a6afdc6"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 588, DateTimeKind.Utc).AddTicks(9950),
                            Number = 200
                        },
                        new
                        {
                            Id = new Guid("3cef97ab-c08c-4876-af22-e7627e319ec4"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 588, DateTimeKind.Utc).AddTicks(9950),
                            Number = 201
                        },
                        new
                        {
                            Id = new Guid("3b0848ff-9e77-4665-a605-a53a309f6e7a"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 588, DateTimeKind.Utc).AddTicks(9950),
                            Number = 202
                        },
                        new
                        {
                            Id = new Guid("4ee853a1-6ce0-48a7-9b0e-e30ff051ea3d"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 588, DateTimeKind.Utc).AddTicks(9960),
                            Number = 203
                        },
                        new
                        {
                            Id = new Guid("e55d21d9-572e-4646-911c-44f9e7a12456"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 588, DateTimeKind.Utc).AddTicks(9960),
                            Number = 204
                        },
                        new
                        {
                            Id = new Guid("d03ef224-e56a-4915-b328-0c6361eb2c66"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 588, DateTimeKind.Utc).AddTicks(9960),
                            Number = 205
                        },
                        new
                        {
                            Id = new Guid("02c16dfc-9c2f-4e6c-984a-254f6cd26936"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 588, DateTimeKind.Utc).AddTicks(9960),
                            Number = 206
                        },
                        new
                        {
                            Id = new Guid("ed6e064a-9231-4d9f-ab95-d828f6ee35d5"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 588, DateTimeKind.Utc).AddTicks(9960),
                            Number = 207
                        },
                        new
                        {
                            Id = new Guid("5cc6aeb7-f5b3-4f51-9be7-7f37b196d9ef"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 588, DateTimeKind.Utc).AddTicks(9970),
                            Number = 208
                        },
                        new
                        {
                            Id = new Guid("231c731c-7f71-4c00-bccf-5c2c64f03a1e"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 588, DateTimeKind.Utc).AddTicks(9970),
                            Number = 209
                        },
                        new
                        {
                            Id = new Guid("fc86dc15-4d97-436e-9902-3d0128afb605"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 588, DateTimeKind.Utc).AddTicks(9970),
                            Number = 210
                        },
                        new
                        {
                            Id = new Guid("9ac76204-9c43-4758-ba85-709599d5c086"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc),
                            Number = 200
                        },
                        new
                        {
                            Id = new Guid("40470fb9-ac7b-46f0-9bc0-43a0d4f4478e"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(10),
                            Number = 201
                        },
                        new
                        {
                            Id = new Guid("dd69139d-5456-4725-9285-8cd4bda63203"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(10),
                            Number = 202
                        },
                        new
                        {
                            Id = new Guid("911c73c4-95ba-4133-8617-7c934c6b36db"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(10),
                            Number = 203
                        },
                        new
                        {
                            Id = new Guid("486ccb32-1f38-4f10-ab7a-7203744b55c4"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(20),
                            Number = 204
                        },
                        new
                        {
                            Id = new Guid("5e888a85-d674-4727-b3d9-e8641ff157a9"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(30),
                            Number = 205
                        },
                        new
                        {
                            Id = new Guid("53f2b763-76cd-4a18-acba-1ea1caf460fe"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(30),
                            Number = 206
                        },
                        new
                        {
                            Id = new Guid("c8c873e7-669a-46d9-9406-513456192bfa"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(40),
                            Number = 207
                        },
                        new
                        {
                            Id = new Guid("054e02f5-3be1-426b-8560-a4bd02d83cbf"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(40),
                            Number = 208
                        },
                        new
                        {
                            Id = new Guid("1dfd674f-0859-417b-9c47-ddc4fde08545"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(40),
                            Number = 209
                        },
                        new
                        {
                            Id = new Guid("69e95ee8-af8b-47eb-a6a1-34cb92ff098d"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(50),
                            Number = 210
                        },
                        new
                        {
                            Id = new Guid("97184f0a-1433-4675-b37b-99aaa84ec966"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(50),
                            Number = 200
                        },
                        new
                        {
                            Id = new Guid("a46220a7-64fc-493d-babb-a5c548d11f95"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(50),
                            Number = 201
                        },
                        new
                        {
                            Id = new Guid("6ac86a87-6b39-4a94-b8f9-4b261a35a18d"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(60),
                            Number = 202
                        },
                        new
                        {
                            Id = new Guid("89d89b7a-0a09-44b2-881c-9cc0a42180e2"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(60),
                            Number = 203
                        },
                        new
                        {
                            Id = new Guid("a911f444-5d22-40ab-9592-f16bad08ad6d"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(60),
                            Number = 204
                        },
                        new
                        {
                            Id = new Guid("bd83aec2-58bf-4468-a282-9060c840ecc8"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(60),
                            Number = 205
                        },
                        new
                        {
                            Id = new Guid("1ce6eb0a-5591-4fe0-aa83-9be6c4bb97bb"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(70),
                            Number = 206
                        },
                        new
                        {
                            Id = new Guid("ea59bbe5-027a-468b-8836-3ce0b42782c3"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(70),
                            Number = 207
                        },
                        new
                        {
                            Id = new Guid("d1e3f3d7-675d-48b5-b0ea-bead6faf4f01"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(70),
                            Number = 208
                        },
                        new
                        {
                            Id = new Guid("2fa9409e-311b-47c8-a06e-ddb5bb3bb99d"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(80),
                            Number = 209
                        },
                        new
                        {
                            Id = new Guid("cdb41023-c1d3-4560-9f33-a1f7c60a0ebc"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(80),
                            Number = 210
                        },
                        new
                        {
                            Id = new Guid("dc74b82b-a82b-44cd-819d-fd1c0beda725"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(80),
                            Number = 200
                        },
                        new
                        {
                            Id = new Guid("06961358-d364-4e65-96c7-1a2f53da9d68"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(80),
                            Number = 201
                        },
                        new
                        {
                            Id = new Guid("cac074ab-0c73-440f-b83e-25dc5b0df244"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(90),
                            Number = 202
                        },
                        new
                        {
                            Id = new Guid("727e8eda-113b-4628-8ffa-4b268e675b32"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(90),
                            Number = 203
                        },
                        new
                        {
                            Id = new Guid("47bb6675-0d23-4528-952e-ceb046e3ee62"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(90),
                            Number = 204
                        },
                        new
                        {
                            Id = new Guid("d392cc41-e63e-48ac-be89-a6a825ece3fb"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(90),
                            Number = 205
                        },
                        new
                        {
                            Id = new Guid("1816ade5-714e-4ea5-9aba-49a4ec7dbe13"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(100),
                            Number = 206
                        },
                        new
                        {
                            Id = new Guid("455f64ad-143d-473f-82ba-5c808560e872"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(100),
                            Number = 207
                        },
                        new
                        {
                            Id = new Guid("3c0c19e8-2fe4-4193-b1d4-cca242feb570"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(100),
                            Number = 208
                        },
                        new
                        {
                            Id = new Guid("317f7a6c-cddb-4ff0-b655-770709f7bfba"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(100),
                            Number = 209
                        },
                        new
                        {
                            Id = new Guid("97d832c6-1230-4c5b-9105-04aabf9c67a9"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(110),
                            Number = 210
                        });
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.Key", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KeyStatus")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("UserId");

                    b.ToTable("Keys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("23594341-cf2a-4eb9-810b-3e21ae72f774"),
                            ClassroomId = new Guid("029da668-f86f-4a64-8d8a-75cbd02423d8"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(730),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("a9db2eb9-bd7e-43b1-81f8-b396496b71c3"),
                            ClassroomId = new Guid("0f821ebe-5456-466c-b394-e28b21c5ebe6"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(740),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("0a30539e-05cd-4ed4-a84f-c4da499071b6"),
                            ClassroomId = new Guid("fac3a3e8-b15c-40e0-a871-3d0f7e5f94b3"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(750),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("478426c2-291d-4900-aef9-af312ba4b2cb"),
                            ClassroomId = new Guid("2897600a-13e1-4b98-9a8b-43659909b1b3"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(750),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("2a8b82d6-aa62-4387-964b-b27964c838b1"),
                            ClassroomId = new Guid("0e195743-b407-4155-a25b-38cbf726985b"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(750),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("89ab668d-6ea5-4d4d-a4ee-5f8cb74b6137"),
                            ClassroomId = new Guid("854e9792-2c57-4707-8be4-398dece1c835"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(750),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("27568a47-15ea-4eac-a651-7f8295780818"),
                            ClassroomId = new Guid("6597fc3b-4b6b-4ef1-94bc-63699d7f1f79"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(760),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("9355964c-69d6-4129-b9e3-6b6325376597"),
                            ClassroomId = new Guid("561e6743-fef8-42ca-84d6-c71a1d35f227"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(760),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("46cfa060-f79b-4845-8c87-7a485da8d348"),
                            ClassroomId = new Guid("c63e6bd0-e712-48e5-86ad-364a46a9cf95"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(760),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("a6c2553a-36bf-41de-ae36-7668739c15ee"),
                            ClassroomId = new Guid("aed7f9e3-a88c-481e-884c-41059113f307"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(760),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("40ffeeec-4581-4526-a9fb-1bd5ae59fb31"),
                            ClassroomId = new Guid("645daf2c-0788-465a-98f2-443ced657d4b"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(770),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("e002c00e-a531-4b36-b52c-3375cb0ab839"),
                            ClassroomId = new Guid("66149d1f-9f3e-4bbd-9ac6-743d7a6afdc6"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(770),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("bb266f8a-9906-4196-9b61-69ecd335da75"),
                            ClassroomId = new Guid("3cef97ab-c08c-4876-af22-e7627e319ec4"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(770),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("7c7b068f-2dd0-4943-9b45-5722ea5da154"),
                            ClassroomId = new Guid("3b0848ff-9e77-4665-a605-a53a309f6e7a"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(770),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("cbb711d6-71ec-4cf7-a925-dbaac2a76076"),
                            ClassroomId = new Guid("4ee853a1-6ce0-48a7-9b0e-e30ff051ea3d"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(780),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("3212e069-6d52-4c89-b3c8-970e33295216"),
                            ClassroomId = new Guid("e55d21d9-572e-4646-911c-44f9e7a12456"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(780),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("e04f6b73-f8e8-44f6-ae1f-d36ec24abd27"),
                            ClassroomId = new Guid("d03ef224-e56a-4915-b328-0c6361eb2c66"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(780),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("4c0d67d4-bf73-4436-a68f-27dacdc5ca90"),
                            ClassroomId = new Guid("02c16dfc-9c2f-4e6c-984a-254f6cd26936"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(780),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("84e1a94a-1803-4104-ba1e-21acedfcebee"),
                            ClassroomId = new Guid("ed6e064a-9231-4d9f-ab95-d828f6ee35d5"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(790),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("8b4f95e0-5633-47b0-b33a-b7a1c0d257c0"),
                            ClassroomId = new Guid("5cc6aeb7-f5b3-4f51-9be7-7f37b196d9ef"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(790),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("426fdce5-cc0b-4b81-9d38-b20cd750e952"),
                            ClassroomId = new Guid("231c731c-7f71-4c00-bccf-5c2c64f03a1e"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(790),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("75a01a64-d28e-4794-8e68-fa250050168f"),
                            ClassroomId = new Guid("fc86dc15-4d97-436e-9902-3d0128afb605"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(800),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("779a9675-98d1-45c2-be69-520b3d6ee68e"),
                            ClassroomId = new Guid("9ac76204-9c43-4758-ba85-709599d5c086"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(800),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("df3ef4ca-d3bd-4be3-acf1-065347be7862"),
                            ClassroomId = new Guid("40470fb9-ac7b-46f0-9bc0-43a0d4f4478e"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(800),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("cda682d8-0ee6-46e3-ad27-c6fb723ddd72"),
                            ClassroomId = new Guid("dd69139d-5456-4725-9285-8cd4bda63203"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(810),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("b6529a39-3740-4931-81a3-322fd981c202"),
                            ClassroomId = new Guid("911c73c4-95ba-4133-8617-7c934c6b36db"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(810),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("a93eef46-b50f-4050-8213-a9975e7c78ed"),
                            ClassroomId = new Guid("486ccb32-1f38-4f10-ab7a-7203744b55c4"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(810),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("60007d23-2ffd-41eb-bf17-4dc362dbcf7e"),
                            ClassroomId = new Guid("5e888a85-d674-4727-b3d9-e8641ff157a9"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(810),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("8c372eea-c817-491c-84dd-6763e4be9a98"),
                            ClassroomId = new Guid("53f2b763-76cd-4a18-acba-1ea1caf460fe"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(820),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("e400d63e-03e6-4f3e-830f-7404af86662b"),
                            ClassroomId = new Guid("c8c873e7-669a-46d9-9406-513456192bfa"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(820),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("06995d50-ea5e-4c77-bc39-4b9bdad610cf"),
                            ClassroomId = new Guid("054e02f5-3be1-426b-8560-a4bd02d83cbf"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(820),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("673b2c00-7f3f-48d1-8704-364337c0e0bb"),
                            ClassroomId = new Guid("1dfd674f-0859-417b-9c47-ddc4fde08545"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(820),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("ac4a7461-6084-41c3-9420-de5b85fccb3b"),
                            ClassroomId = new Guid("69e95ee8-af8b-47eb-a6a1-34cb92ff098d"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(830),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("770c1b10-38af-40a7-8712-6ef4bf3f02d3"),
                            ClassroomId = new Guid("97184f0a-1433-4675-b37b-99aaa84ec966"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(830),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("1c7f4d4c-cddb-41ff-9ca3-98c554c530e2"),
                            ClassroomId = new Guid("a46220a7-64fc-493d-babb-a5c548d11f95"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(830),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("13508d9d-4fe0-4ca5-a262-7c8219c3ced4"),
                            ClassroomId = new Guid("6ac86a87-6b39-4a94-b8f9-4b261a35a18d"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(830),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("6d2a19aa-6745-45f7-9ac7-57717a1f387c"),
                            ClassroomId = new Guid("89d89b7a-0a09-44b2-881c-9cc0a42180e2"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(840),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("67fcd0da-2946-4043-bb10-77be1d5892cc"),
                            ClassroomId = new Guid("a911f444-5d22-40ab-9592-f16bad08ad6d"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(840),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("18a65db9-f47e-4c55-ae22-a3685237fe96"),
                            ClassroomId = new Guid("bd83aec2-58bf-4468-a282-9060c840ecc8"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(840),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("5be5d8ac-58ad-40d9-9e00-960e747f7273"),
                            ClassroomId = new Guid("1ce6eb0a-5591-4fe0-aa83-9be6c4bb97bb"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(840),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("134f0b04-5f5c-4971-9c6f-7760509be75f"),
                            ClassroomId = new Guid("ea59bbe5-027a-468b-8836-3ce0b42782c3"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(840),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("18644e06-d34f-400e-aeff-ffd595cf86a9"),
                            ClassroomId = new Guid("d1e3f3d7-675d-48b5-b0ea-bead6faf4f01"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(850),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("b36921b9-d88a-47ad-84ba-3f61ff34825a"),
                            ClassroomId = new Guid("2fa9409e-311b-47c8-a06e-ddb5bb3bb99d"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(850),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("c61c8793-9f7a-40ee-82c2-36b04c548802"),
                            ClassroomId = new Guid("cdb41023-c1d3-4560-9f33-a1f7c60a0ebc"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(850),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("f4b7e5a2-04d4-4c68-99a3-0cd0523a8e2f"),
                            ClassroomId = new Guid("dc74b82b-a82b-44cd-819d-fd1c0beda725"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(850),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("482c2304-29a3-462e-9e65-751480fbd08a"),
                            ClassroomId = new Guid("06961358-d364-4e65-96c7-1a2f53da9d68"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(860),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("6078dcc9-c52d-4563-b0ad-d9fdee023463"),
                            ClassroomId = new Guid("cac074ab-0c73-440f-b83e-25dc5b0df244"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(860),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("f82d953f-09be-4aad-ba4a-5c463e21e56c"),
                            ClassroomId = new Guid("727e8eda-113b-4628-8ffa-4b268e675b32"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(860),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("2e0d2170-a102-43f0-8138-51b205ddf388"),
                            ClassroomId = new Guid("47bb6675-0d23-4528-952e-ceb046e3ee62"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(860),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("653ea1b9-7e2e-49a5-bd67-47658e5dd353"),
                            ClassroomId = new Guid("d392cc41-e63e-48ac-be89-a6a825ece3fb"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(870),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("bf1a98a7-f68d-46bf-87ce-b1361ad155a5"),
                            ClassroomId = new Guid("1816ade5-714e-4ea5-9aba-49a4ec7dbe13"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(870),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("180ab39b-53bd-4748-85af-fad2c9fccf33"),
                            ClassroomId = new Guid("455f64ad-143d-473f-82ba-5c808560e872"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(870),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("3e174f70-cb28-4204-8dda-641233b47296"),
                            ClassroomId = new Guid("3c0c19e8-2fe4-4193-b1d4-cca242feb570"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(880),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("dd73f946-1896-4564-bdb9-e24a2cd528c0"),
                            ClassroomId = new Guid("317f7a6c-cddb-4ff0-b655-770709f7bfba"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(880),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("95dd280b-f954-4dc4-8725-c500f5ebe4f8"),
                            ClassroomId = new Guid("97d832c6-1230-4c5b-9105-04aabf9c67a9"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 589, DateTimeKind.Utc).AddTicks(880),
                            KeyStatus = 0
                        });
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.KeyRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("EndDateOfRecurrence")
                        .HasColumnType("date");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("UserId");

                    b.ToTable("KeyRequests");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.RegistrationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RegistrationRequests");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.TransferKeyRequest", b =>
                {
                    b.Property<Guid>("KeyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid");

                    b.HasKey("KeyId", "RecipientId");

                    b.HasIndex("RecipientId");

                    b.ToTable("TransferKeyRequests");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<int?>("UserRole")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ae3842de-d8c5-400e-81a6-63e1a826668b"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 145, DateTimeKind.Utc).AddTicks(6950),
                            Email = "admin@gmail.com",
                            FullName = "admin",
                            Gender = 0,
                            Password = "$2a$11$GKCr5qLxSWYBT1tz.isEvO5U0MdJaIjI9Ufh/DygenvdGo9QS6B42",
                            UserRole = 3
                        },
                        new
                        {
                            Id = new Guid("7946583b-13ef-406b-8a7a-6738c3105987"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 254, DateTimeKind.Utc).AddTicks(8240),
                            Email = "dean@gmail.com",
                            FullName = "dean",
                            Gender = 0,
                            Password = "$2a$11$vG8wBr7.dsgUMc3/aOXut.BQJOLgHb5g1ocKJ7IM4XHBlYRYD.suW",
                            UserRole = 2
                        },
                        new
                        {
                            Id = new Guid("51540c49-d30f-45d0-9abf-de9bc9a8d2bb"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 369, DateTimeKind.Utc).AddTicks(2810),
                            Email = "teacher@gmail.com",
                            FullName = "teacher",
                            Gender = 0,
                            Password = "$2a$11$azMjJzgYlvtVrHhjJxJpsu.ymmo9w9UC/SKp9dO.5Q.k4ehd9DNXi",
                            UserRole = 1
                        },
                        new
                        {
                            Id = new Guid("feecb044-7935-4e55-9245-445e258384ee"),
                            CreateTime = new DateTime(2024, 3, 10, 3, 57, 34, 480, DateTimeKind.Utc).AddTicks(6950),
                            Email = "student@gmail.com",
                            FullName = "student",
                            Gender = 0,
                            Password = "$2a$11$UGdyI7X5aPZtmCCz9MDhCe61CaAMtAjeykU0YZxa48gCv.1IxNnUy",
                            UserRole = 0
                        });
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.Key", b =>
                {
                    b.HasOne("ClassroomBooking.Domain.Entities.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassroomBooking.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Classroom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.KeyRequest", b =>
                {
                    b.HasOne("ClassroomBooking.Domain.Entities.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassroomBooking.Domain.Entities.User", "User")
                        .WithMany("Requests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.RegistrationRequest", b =>
                {
                    b.HasOne("ClassroomBooking.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.TransferKeyRequest", b =>
                {
                    b.HasOne("ClassroomBooking.Domain.Entities.Key", "Key")
                        .WithMany()
                        .HasForeignKey("KeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassroomBooking.Domain.Entities.User", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Key");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.User", b =>
                {
                    b.Navigation("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
