// <auto-generated />
using System;
using ClassroomBooking.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClassroomBooking.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240302045405_Delete is recurring field")]
    partial class Deleteisrecurringfield
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.Classroom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Building")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Classrooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e446d1bb-d49b-40d1-8827-8d8e8de6d73d"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8336),
                            Number = 200
                        },
                        new
                        {
                            Id = new Guid("69d22e63-2525-48b1-ab7e-09310a02e386"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8370),
                            Number = 201
                        },
                        new
                        {
                            Id = new Guid("ea1f2717-bc56-4149-ab6e-2440dfc9e574"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8372),
                            Number = 202
                        },
                        new
                        {
                            Id = new Guid("986b65dd-ed95-453e-ad81-12e3defc5ca2"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8373),
                            Number = 203
                        },
                        new
                        {
                            Id = new Guid("88a723b4-7b98-475f-bd68-e6476565c827"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8374),
                            Number = 204
                        },
                        new
                        {
                            Id = new Guid("20c9956c-d2e7-4654-bdf2-a7b1b248536f"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8401),
                            Number = 205
                        },
                        new
                        {
                            Id = new Guid("2a2ed7d6-4221-4e4b-8a76-ef7d76c47707"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8402),
                            Number = 206
                        },
                        new
                        {
                            Id = new Guid("4dd481e1-aea8-4ef2-a212-056f1484b408"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8404),
                            Number = 207
                        },
                        new
                        {
                            Id = new Guid("b4de0889-30db-4c78-bcea-ad7503ee982a"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8405),
                            Number = 208
                        },
                        new
                        {
                            Id = new Guid("70404744-ee3a-4eda-b458-3f0d3c9d932d"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8407),
                            Number = 209
                        },
                        new
                        {
                            Id = new Guid("0754f3e1-3515-4553-b2a8-16c52c5130fb"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8409),
                            Number = 210
                        },
                        new
                        {
                            Id = new Guid("1214b8e5-2b1f-4790-b4b7-a98c078c978a"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8411),
                            Number = 200
                        },
                        new
                        {
                            Id = new Guid("0f575359-5814-4609-bb30-c663b05338ed"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8412),
                            Number = 201
                        },
                        new
                        {
                            Id = new Guid("833d611b-e232-43ea-881d-f1b87686b50d"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8416),
                            Number = 202
                        },
                        new
                        {
                            Id = new Guid("690756ba-88ad-4f1f-9daf-a6869b168be3"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8417),
                            Number = 203
                        },
                        new
                        {
                            Id = new Guid("c11d8194-3a60-43ff-8f90-615ccafdfc3c"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8418),
                            Number = 204
                        },
                        new
                        {
                            Id = new Guid("fecf6b80-40e0-495e-b2e6-cdeb7f91d71d"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8420),
                            Number = 205
                        },
                        new
                        {
                            Id = new Guid("207b4582-a685-4208-9a88-997c8dc92f5b"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8422),
                            Number = 206
                        },
                        new
                        {
                            Id = new Guid("7ca539d6-c053-4f64-aed1-30feecc9316c"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8423),
                            Number = 207
                        },
                        new
                        {
                            Id = new Guid("60479f87-6ba7-465d-af78-634d0c5cc82b"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8424),
                            Number = 208
                        },
                        new
                        {
                            Id = new Guid("4d2a603a-6f4b-428a-85cb-40f7ffbff3ba"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8425),
                            Number = 209
                        },
                        new
                        {
                            Id = new Guid("43d2fd6c-2261-404b-bc3e-e92fd724e384"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8429),
                            Number = 210
                        },
                        new
                        {
                            Id = new Guid("87f2771f-734d-4339-a88b-14e677357782"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8430),
                            Number = 200
                        },
                        new
                        {
                            Id = new Guid("05330fd4-2509-44ed-ad97-a72d3e5aefe9"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8431),
                            Number = 201
                        },
                        new
                        {
                            Id = new Guid("1fe25d1a-795f-4a2f-9871-18eb3f775d98"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8432),
                            Number = 202
                        },
                        new
                        {
                            Id = new Guid("05779436-1d6a-472a-a743-53e638a0f4cd"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8433),
                            Number = 203
                        },
                        new
                        {
                            Id = new Guid("6d1e58ce-d789-41df-b978-8202e56dfe3f"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8434),
                            Number = 204
                        },
                        new
                        {
                            Id = new Guid("f49deeb1-c78d-4804-ab60-54f05ec213b2"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8533),
                            Number = 205
                        },
                        new
                        {
                            Id = new Guid("2e598d0e-e449-46b5-a3aa-59f1bab00f0f"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8554),
                            Number = 206
                        },
                        new
                        {
                            Id = new Guid("0c993341-f269-4c68-948c-e41b5f1252aa"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8558),
                            Number = 207
                        },
                        new
                        {
                            Id = new Guid("8070e7c2-b9ac-4e2a-8229-a3fcacb5cfe9"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8559),
                            Number = 208
                        },
                        new
                        {
                            Id = new Guid("03377b7d-f83d-45f5-9b15-595773610f45"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8560),
                            Number = 209
                        },
                        new
                        {
                            Id = new Guid("d41f2273-ba0c-47da-aa96-0005f8e190db"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8562),
                            Number = 210
                        },
                        new
                        {
                            Id = new Guid("ab2c3b70-93eb-4fda-af8c-1b472c0e61b1"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8565),
                            Number = 200
                        },
                        new
                        {
                            Id = new Guid("05bba24c-525c-4fc7-b000-53f822a5624f"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8566),
                            Number = 201
                        },
                        new
                        {
                            Id = new Guid("fb08a950-c382-4de5-a833-07c38aa925b3"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8567),
                            Number = 202
                        },
                        new
                        {
                            Id = new Guid("493d60e0-d865-42b4-bb9e-cf18839bd447"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8568),
                            Number = 203
                        },
                        new
                        {
                            Id = new Guid("30f6d5ed-2de2-4e53-a362-e672fb9b6468"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8572),
                            Number = 204
                        },
                        new
                        {
                            Id = new Guid("3b74d744-6482-4eb3-b591-3978988476ce"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8573),
                            Number = 205
                        },
                        new
                        {
                            Id = new Guid("28f43699-5103-4305-af7d-918d520f8acb"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8574),
                            Number = 206
                        },
                        new
                        {
                            Id = new Guid("7584691e-1b69-4e87-bc54-5e23543ea27f"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8575),
                            Number = 207
                        },
                        new
                        {
                            Id = new Guid("c8c262ec-72ae-4bc1-ba45-2787a12fa87b"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8576),
                            Number = 208
                        },
                        new
                        {
                            Id = new Guid("71e8086a-2912-4beb-8ffb-787d9c3774af"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8577),
                            Number = 209
                        },
                        new
                        {
                            Id = new Guid("021f3121-2a8d-4380-87a4-46c24f369091"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8578),
                            Number = 210
                        },
                        new
                        {
                            Id = new Guid("284a99e6-57c9-408d-b745-3ccc42135c91"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8580),
                            Number = 200
                        },
                        new
                        {
                            Id = new Guid("4a96fb6b-b16e-4695-b8c3-5947052a4ac1"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8584),
                            Number = 201
                        },
                        new
                        {
                            Id = new Guid("3d52ddb5-b5e0-4b88-9b05-85e6ea41726b"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8585),
                            Number = 202
                        },
                        new
                        {
                            Id = new Guid("f17955ba-0ffd-4b5b-9674-dfacbb04c265"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8586),
                            Number = 203
                        },
                        new
                        {
                            Id = new Guid("0af21a18-cb5d-438d-9950-c74ba7dd7195"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8587),
                            Number = 204
                        },
                        new
                        {
                            Id = new Guid("cee10807-33e2-45fb-a0dd-52e7bf41ed87"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8588),
                            Number = 205
                        },
                        new
                        {
                            Id = new Guid("83ed74dd-c50f-45ac-8fc9-db8eb506d748"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8589),
                            Number = 206
                        },
                        new
                        {
                            Id = new Guid("8b31ffc9-1f14-49ab-a40e-6abbb0a1b277"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8590),
                            Number = 207
                        },
                        new
                        {
                            Id = new Guid("d1e8157d-7318-4e0e-bb9d-e2817289db49"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8591),
                            Number = 208
                        },
                        new
                        {
                            Id = new Guid("934c2cdb-1f46-4b84-8b32-442a7b0626ba"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8595),
                            Number = 209
                        },
                        new
                        {
                            Id = new Guid("81fce5b8-c18f-453e-9bdb-f2acd4956b21"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(8596),
                            Number = 210
                        });
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.Key", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KeyStatus")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("UserId");

                    b.ToTable("Keys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("26e7c8cd-5d68-4af3-af2c-4c6315fa971b"),
                            ClassroomId = new Guid("e446d1bb-d49b-40d1-8827-8d8e8de6d73d"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9705),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("3fcd542d-8a7e-46ce-8465-fafe2fb2ae7e"),
                            ClassroomId = new Guid("69d22e63-2525-48b1-ab7e-09310a02e386"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9714),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("f096773f-6d9d-4039-8469-99ea1151a555"),
                            ClassroomId = new Guid("ea1f2717-bc56-4149-ab6e-2440dfc9e574"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9715),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("c80c923f-c91f-48cf-9f23-9a7c075425a6"),
                            ClassroomId = new Guid("986b65dd-ed95-453e-ad81-12e3defc5ca2"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9717),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("368b8dab-be80-47f2-843e-7c4b816e8d94"),
                            ClassroomId = new Guid("88a723b4-7b98-475f-bd68-e6476565c827"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9718),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("01b7049d-66de-4f07-954a-c500424f8a67"),
                            ClassroomId = new Guid("20c9956c-d2e7-4654-bdf2-a7b1b248536f"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9721),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("d2518d4b-19e0-491c-9064-1c034a06fc71"),
                            ClassroomId = new Guid("2a2ed7d6-4221-4e4b-8a76-ef7d76c47707"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9726),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("0a8b9d04-2a2f-4d1a-a4fa-374a7d9a8e1a"),
                            ClassroomId = new Guid("4dd481e1-aea8-4ef2-a212-056f1484b408"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9727),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("4348876a-0691-4f43-8129-57dcc58d8791"),
                            ClassroomId = new Guid("b4de0889-30db-4c78-bcea-ad7503ee982a"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9729),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("0a559c17-fe5c-418c-a058-1066846565a3"),
                            ClassroomId = new Guid("70404744-ee3a-4eda-b458-3f0d3c9d932d"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9731),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("f0d50435-5624-41cd-86f3-f696db85f951"),
                            ClassroomId = new Guid("0754f3e1-3515-4553-b2a8-16c52c5130fb"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9732),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("a80d519c-71c2-4a6a-8cd8-7faeb03b13ac"),
                            ClassroomId = new Guid("1214b8e5-2b1f-4790-b4b7-a98c078c978a"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9733),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("9afb3eeb-6401-4485-8fe7-7f1c9c358f09"),
                            ClassroomId = new Guid("0f575359-5814-4609-bb30-c663b05338ed"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9735),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("c2093c41-a3a6-4657-9786-e429547145a2"),
                            ClassroomId = new Guid("833d611b-e232-43ea-881d-f1b87686b50d"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9736),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("2f68e75c-bbd9-443d-99a3-5a7e3a6e6f98"),
                            ClassroomId = new Guid("690756ba-88ad-4f1f-9daf-a6869b168be3"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9740),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("138fe27e-04ac-4e72-b22e-32f29a2a10d2"),
                            ClassroomId = new Guid("c11d8194-3a60-43ff-8f90-615ccafdfc3c"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9741),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("7d35605d-0777-491c-b10f-e3278c335abc"),
                            ClassroomId = new Guid("fecf6b80-40e0-495e-b2e6-cdeb7f91d71d"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9742),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("e0d25e7f-2760-417a-940b-9320ef0b1263"),
                            ClassroomId = new Guid("207b4582-a685-4208-9a88-997c8dc92f5b"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9745),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("eec38b63-3de0-4554-92ca-522c0d8bc855"),
                            ClassroomId = new Guid("7ca539d6-c053-4f64-aed1-30feecc9316c"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9746),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("1e2401c8-8d91-46a4-8993-9a72c1b3ed07"),
                            ClassroomId = new Guid("60479f87-6ba7-465d-af78-634d0c5cc82b"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9747),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("40b6a5c4-a247-434d-949b-d75672284dac"),
                            ClassroomId = new Guid("4d2a603a-6f4b-428a-85cb-40f7ffbff3ba"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9748),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("06783507-c52f-4fc5-bf93-4c41b282ce7d"),
                            ClassroomId = new Guid("43d2fd6c-2261-404b-bc3e-e92fd724e384"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9750),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("51a568fd-0ae5-4705-ac07-d749626d805e"),
                            ClassroomId = new Guid("87f2771f-734d-4339-a88b-14e677357782"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9753),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("bd4daa24-6e4d-4528-a195-317782cdd4bb"),
                            ClassroomId = new Guid("05330fd4-2509-44ed-ad97-a72d3e5aefe9"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9754),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("81c71b07-1314-4df1-94e3-4fd291422c60"),
                            ClassroomId = new Guid("1fe25d1a-795f-4a2f-9871-18eb3f775d98"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9756),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("b2a7460e-727c-45d1-9878-73a032d6aa79"),
                            ClassroomId = new Guid("05779436-1d6a-472a-a743-53e638a0f4cd"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9757),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("3b41ad47-e8a8-40a9-9c34-f0b3a27f644a"),
                            ClassroomId = new Guid("6d1e58ce-d789-41df-b978-8202e56dfe3f"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9758),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("a1bc8a50-0c3e-4eb9-a355-9d95bb8bc930"),
                            ClassroomId = new Guid("f49deeb1-c78d-4804-ab60-54f05ec213b2"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9759),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("9f75fe08-eeb5-41d5-a26f-e913598e2ef1"),
                            ClassroomId = new Guid("2e598d0e-e449-46b5-a3aa-59f1bab00f0f"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9760),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("3fe58b5b-e352-4970-97c9-adfce660d56e"),
                            ClassroomId = new Guid("0c993341-f269-4c68-948c-e41b5f1252aa"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9762),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("c0bb17ea-4f58-4bbb-9c93-1446bfa6ee05"),
                            ClassroomId = new Guid("8070e7c2-b9ac-4e2a-8229-a3fcacb5cfe9"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9765),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("2e95f873-5d6d-4f18-9bc9-e05fa628402a"),
                            ClassroomId = new Guid("03377b7d-f83d-45f5-9b15-595773610f45"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9767),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("f7e1065b-cc5b-482f-914b-ccc436f915e1"),
                            ClassroomId = new Guid("d41f2273-ba0c-47da-aa96-0005f8e190db"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9768),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("fc9fb605-4768-475c-8bf3-e425f39f411f"),
                            ClassroomId = new Guid("ab2c3b70-93eb-4fda-af8c-1b472c0e61b1"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9770),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("de33eb4a-dbb9-4a6b-9a64-27ff4afcab53"),
                            ClassroomId = new Guid("05bba24c-525c-4fc7-b000-53f822a5624f"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9771),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("c9327c1b-8ab9-431a-80d7-15740245a98e"),
                            ClassroomId = new Guid("fb08a950-c382-4de5-a833-07c38aa925b3"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9772),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("0ee588f0-0c5f-4290-8d88-e986047a21f6"),
                            ClassroomId = new Guid("493d60e0-d865-42b4-bb9e-cf18839bd447"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9774),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("8757e5ae-c1e8-4a3a-a6b2-676acda3dee6"),
                            ClassroomId = new Guid("30f6d5ed-2de2-4e53-a362-e672fb9b6468"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9775),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("2f525b0c-510a-45b6-b3bb-164d0d255d5b"),
                            ClassroomId = new Guid("3b74d744-6482-4eb3-b591-3978988476ce"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9779),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("4d76c165-3a09-4c74-8830-16691c110996"),
                            ClassroomId = new Guid("28f43699-5103-4305-af7d-918d520f8acb"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9780),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("04e938ab-6b22-412e-a8f3-42920dfd3b19"),
                            ClassroomId = new Guid("7584691e-1b69-4e87-bc54-5e23543ea27f"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9781),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("0bafc1a9-3535-46b1-b8eb-870c4c2c009f"),
                            ClassroomId = new Guid("c8c262ec-72ae-4bc1-ba45-2787a12fa87b"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9782),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("1e27b238-fa68-48de-96ff-944afd3275af"),
                            ClassroomId = new Guid("71e8086a-2912-4beb-8ffb-787d9c3774af"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9783),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("b54d1560-2661-4a6a-bf94-3be29714c68f"),
                            ClassroomId = new Guid("021f3121-2a8d-4380-87a4-46c24f369091"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9784),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("bd845890-5642-42b5-94ec-f2063d6ffede"),
                            ClassroomId = new Guid("284a99e6-57c9-408d-b745-3ccc42135c91"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9785),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("d8124308-04f3-4de4-8735-a9b420a9db55"),
                            ClassroomId = new Guid("4a96fb6b-b16e-4695-b8c3-5947052a4ac1"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9786),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("a780d7eb-1eb5-483f-ac87-8fcd13d742b6"),
                            ClassroomId = new Guid("3d52ddb5-b5e0-4b88-9b05-85e6ea41726b"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9790),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("c6b94177-4022-48ea-8940-504cf3ea3fc9"),
                            ClassroomId = new Guid("f17955ba-0ffd-4b5b-9674-dfacbb04c265"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9791),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("8f4377aa-f850-4e18-b346-c7dfebe994c3"),
                            ClassroomId = new Guid("0af21a18-cb5d-438d-9950-c74ba7dd7195"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9792),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("30550ea0-dc6e-4031-a39d-5e899dc46344"),
                            ClassroomId = new Guid("cee10807-33e2-45fb-a0dd-52e7bf41ed87"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9793),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("d96ced3e-1dbd-4234-907c-dc4ef5c326ed"),
                            ClassroomId = new Guid("83ed74dd-c50f-45ac-8fc9-db8eb506d748"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9794),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("215eddfb-c2ca-4be3-8af6-94f67a1dea42"),
                            ClassroomId = new Guid("8b31ffc9-1f14-49ab-a40e-6abbb0a1b277"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9795),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("fa664f91-ae92-48e9-a1cb-c09edcca3806"),
                            ClassroomId = new Guid("d1e8157d-7318-4e0e-bb9d-e2817289db49"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9796),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("917e593b-1496-41b8-b76a-61eb0e36bf0a"),
                            ClassroomId = new Guid("934c2cdb-1f46-4b84-8b32-442a7b0626ba"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9798),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("632b93b0-0eba-498d-825c-15e9245ffa82"),
                            ClassroomId = new Guid("81fce5b8-c18f-453e-9bdb-f2acd4956b21"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 289, DateTimeKind.Utc).AddTicks(9801),
                            KeyStatus = 0
                        });
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.KeyRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("UserId");

                    b.ToTable("KeyRequests");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.RegistrationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RegistrationRequests");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<int?>("UserRole")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("300acba5-b104-4a2c-9854-11889f153a82"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 3, 791, DateTimeKind.Utc).AddTicks(8638),
                            Email = "admin@gmail.com",
                            FullName = "admin",
                            Gender = 0,
                            Password = "$2a$11$p1X.HHnLq6dVIdgBcIkvPu1CVDYhI6DWw8TQIY/W7MPhMTrteFHIG",
                            UserRole = 3
                        },
                        new
                        {
                            Id = new Guid("4fefe082-1e41-42aa-aa8b-bdb2e56e9b48"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 3, 918, DateTimeKind.Utc).AddTicks(6284),
                            Email = "dean@gmail.com",
                            FullName = "dean",
                            Gender = 0,
                            Password = "$2a$11$12jl9hoWztwm6s7wyCit1O4ldwrC3dvO8xqDrqeKjVAuQ8NUGfpGS",
                            UserRole = 2
                        },
                        new
                        {
                            Id = new Guid("30a1e9fb-3a4f-474e-8a56-3820baaf35dc"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 41, DateTimeKind.Utc).AddTicks(7566),
                            Email = "teacher@gmail.com",
                            FullName = "teacher",
                            Gender = 0,
                            Password = "$2a$11$Wuby2Qr0wnPkfyQveDaBBu6bGsqLgEDzytY0U//IpJp3mlP9HslZ6",
                            UserRole = 1
                        },
                        new
                        {
                            Id = new Guid("533d38d6-bb99-4ac3-a0d1-78b19300dd7c"),
                            CreateTime = new DateTime(2024, 3, 2, 4, 54, 4, 167, DateTimeKind.Utc).AddTicks(5974),
                            Email = "student@gmail.com",
                            FullName = "student",
                            Gender = 0,
                            Password = "$2a$11$JwAHRBkgEM8GfaZAoNnZgOyHUH6.h7b3r7RHwAEZLSd2dCkKEZBj6",
                            UserRole = 0
                        });
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.Key", b =>
                {
                    b.HasOne("ClassroomBooking.Domain.Entities.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassroomBooking.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Classroom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.KeyRequest", b =>
                {
                    b.HasOne("ClassroomBooking.Domain.Entities.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassroomBooking.Domain.Entities.User", "User")
                        .WithMany("Requests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.RegistrationRequest", b =>
                {
                    b.HasOne("ClassroomBooking.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.User", b =>
                {
                    b.Navigation("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
