// <auto-generated />
using System;
using ClassroomBooking.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClassroomBooking.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.Classroom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Building")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Classrooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b198921a-3d68-4067-a5b6-19f086b1d30b"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8590),
                            Number = 200
                        },
                        new
                        {
                            Id = new Guid("7bc4b7fb-855c-406f-8964-0e641a54ce18"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8600),
                            Number = 201
                        },
                        new
                        {
                            Id = new Guid("c49ea702-42dd-4524-a95b-4298ab4f4a69"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8600),
                            Number = 202
                        },
                        new
                        {
                            Id = new Guid("51024c7b-3fb4-49e0-b907-485f4adb6435"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8600),
                            Number = 203
                        },
                        new
                        {
                            Id = new Guid("d10fdbdf-b229-435f-82cc-347c09a7c8be"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8610),
                            Number = 204
                        },
                        new
                        {
                            Id = new Guid("03403da8-e010-4490-87f2-0d406ee95e44"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8610),
                            Number = 205
                        },
                        new
                        {
                            Id = new Guid("2516201c-236f-4071-ae4f-0163b60d945e"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8620),
                            Number = 206
                        },
                        new
                        {
                            Id = new Guid("cf5300fb-1880-443d-a731-80682c7a889d"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8620),
                            Number = 207
                        },
                        new
                        {
                            Id = new Guid("5e366b30-082b-4aab-93a2-1bb70bb2d10c"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8620),
                            Number = 208
                        },
                        new
                        {
                            Id = new Guid("f2425a1e-0433-4508-aed4-3f63f3a148f2"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8620),
                            Number = 209
                        },
                        new
                        {
                            Id = new Guid("80f8dce5-662a-4c5a-86ed-98da8643109d"),
                            Building = 1,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8630),
                            Number = 210
                        },
                        new
                        {
                            Id = new Guid("a60a6ac1-99e7-468d-bcd3-c3b6d3bf215d"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8630),
                            Number = 200
                        },
                        new
                        {
                            Id = new Guid("b7abc369-e304-4e18-a953-c148beac05d8"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8630),
                            Number = 201
                        },
                        new
                        {
                            Id = new Guid("8224b0a9-9cc6-43d8-9acc-98c5d7db6f89"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8630),
                            Number = 202
                        },
                        new
                        {
                            Id = new Guid("7ae880b6-0914-4b1e-b276-7fb7af52a19f"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8640),
                            Number = 203
                        },
                        new
                        {
                            Id = new Guid("6413d3a2-4e85-4c18-b7aa-6e33d14e7638"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8640),
                            Number = 204
                        },
                        new
                        {
                            Id = new Guid("2d10b0f7-182d-4ec6-9fd6-59890a5c2c6c"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8640),
                            Number = 205
                        },
                        new
                        {
                            Id = new Guid("a28105ec-9132-47d2-b769-c4472e41b4df"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8640),
                            Number = 206
                        },
                        new
                        {
                            Id = new Guid("6254a611-5cc5-4b71-b6f6-d53351c7bb44"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8650),
                            Number = 207
                        },
                        new
                        {
                            Id = new Guid("600cae99-cafb-4d82-92cb-286d88a8fed5"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8650),
                            Number = 208
                        },
                        new
                        {
                            Id = new Guid("d7d60ae3-2253-47eb-b8d2-592ff3eff606"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8650),
                            Number = 209
                        },
                        new
                        {
                            Id = new Guid("ecf56071-7ce2-430f-a2e1-219b3804a23e"),
                            Building = 2,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8650),
                            Number = 210
                        },
                        new
                        {
                            Id = new Guid("4fbcdace-7d82-422f-a517-f28a22247222"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8700),
                            Number = 200
                        },
                        new
                        {
                            Id = new Guid("40d13ea5-1f8c-4390-82b0-fc6ab0b047e5"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8700),
                            Number = 201
                        },
                        new
                        {
                            Id = new Guid("1e37ba0d-e660-4d32-9f3e-1f355dab53d1"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8700),
                            Number = 202
                        },
                        new
                        {
                            Id = new Guid("1eb75642-ba0f-4072-a7c2-f2d9f7df2c07"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8700),
                            Number = 203
                        },
                        new
                        {
                            Id = new Guid("e60c9e86-ef8e-4f45-ac07-4e6078df11f0"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8720),
                            Number = 204
                        },
                        new
                        {
                            Id = new Guid("d3f30e56-1492-4f05-b3cb-f28b8830c6c9"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8720),
                            Number = 205
                        },
                        new
                        {
                            Id = new Guid("48a31bc3-8078-40b8-807f-b0a1b08f2d94"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8720),
                            Number = 206
                        },
                        new
                        {
                            Id = new Guid("25a765bc-66a8-4411-b1ca-1be8a5b5c37d"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8730),
                            Number = 207
                        },
                        new
                        {
                            Id = new Guid("1d62e2b8-97b6-4207-8f61-39357b9b7499"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8730),
                            Number = 208
                        },
                        new
                        {
                            Id = new Guid("e2990d44-ca16-4f23-9aa1-203c47e11b13"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8730),
                            Number = 209
                        },
                        new
                        {
                            Id = new Guid("aa4b69ec-024b-4f23-bb61-dd1f8982e0de"),
                            Building = 3,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8790),
                            Number = 210
                        },
                        new
                        {
                            Id = new Guid("949542b2-14e5-4944-aa15-db194000003b"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8790),
                            Number = 200
                        },
                        new
                        {
                            Id = new Guid("ebd66a9e-0813-4d77-9498-f66933d46412"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8800),
                            Number = 201
                        },
                        new
                        {
                            Id = new Guid("72d8f80c-e611-4af9-889e-8e4c5d870b74"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8800),
                            Number = 202
                        },
                        new
                        {
                            Id = new Guid("47cef1b2-77df-4a3f-971a-13ac866934c2"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8800),
                            Number = 203
                        },
                        new
                        {
                            Id = new Guid("44bdcfcd-7501-45f8-b181-012ee37c1ce1"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8810),
                            Number = 204
                        },
                        new
                        {
                            Id = new Guid("84e3da95-9372-4af6-b4c4-64c397c4fb96"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8810),
                            Number = 205
                        },
                        new
                        {
                            Id = new Guid("b779915d-52df-4e0d-8173-bfde01304a48"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8810),
                            Number = 206
                        },
                        new
                        {
                            Id = new Guid("bc386832-bad5-429b-a350-eb3a5b9063e8"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8820),
                            Number = 207
                        },
                        new
                        {
                            Id = new Guid("db4002f8-2661-4cdd-b377-dd017e779462"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8820),
                            Number = 208
                        },
                        new
                        {
                            Id = new Guid("741be67c-e1c9-447f-ba7f-7aa8f4c3c5f8"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8820),
                            Number = 209
                        },
                        new
                        {
                            Id = new Guid("bf497f2a-a004-4abf-9e1d-36f1659c189a"),
                            Building = 4,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8830),
                            Number = 210
                        },
                        new
                        {
                            Id = new Guid("eb3820d2-a6da-4ac4-a403-b3bd8a0c8d4a"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8830),
                            Number = 200
                        },
                        new
                        {
                            Id = new Guid("fb1e4faf-a95e-451c-99b9-373177f0651f"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8830),
                            Number = 201
                        },
                        new
                        {
                            Id = new Guid("f000260e-fb82-4b2c-84a6-eba34cd5f1f5"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8840),
                            Number = 202
                        },
                        new
                        {
                            Id = new Guid("304ce9d5-6ff6-4a62-b418-ab4988cd659b"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8840),
                            Number = 203
                        },
                        new
                        {
                            Id = new Guid("a690bd67-4949-4382-b2bd-a4cd6dd0b0f7"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8840),
                            Number = 204
                        },
                        new
                        {
                            Id = new Guid("1fd9d87e-7176-4242-a1a2-302724e6a1ec"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8850),
                            Number = 205
                        },
                        new
                        {
                            Id = new Guid("734788b2-5bfc-4d76-897c-40a918106c16"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8850),
                            Number = 206
                        },
                        new
                        {
                            Id = new Guid("b2a855f1-6263-4c54-83d7-24d30d280563"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8850),
                            Number = 207
                        },
                        new
                        {
                            Id = new Guid("6acc7531-cc7a-4ab6-87de-d2f7af5d6329"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8860),
                            Number = 208
                        },
                        new
                        {
                            Id = new Guid("d06ca3f8-a3e1-4cfa-8925-44d007dc4db3"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8860),
                            Number = 209
                        },
                        new
                        {
                            Id = new Guid("66a27a07-a8d5-43ae-be6c-f8690c013f94"),
                            Building = 5,
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(8860),
                            Number = 210
                        });
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.Key", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KeyStatus")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("UserId");

                    b.ToTable("Keys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b629ee70-5763-44be-8367-06c300b74a34"),
                            ClassroomId = new Guid("b198921a-3d68-4067-a5b6-19f086b1d30b"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9360),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("cee19b4f-f133-453d-ab1c-ed54948684f4"),
                            ClassroomId = new Guid("7bc4b7fb-855c-406f-8964-0e641a54ce18"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9370),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("cb3c1413-53f7-4fa5-b08a-f556c556914c"),
                            ClassroomId = new Guid("c49ea702-42dd-4524-a95b-4298ab4f4a69"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9370),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("4dcc2061-eaeb-4052-9a61-665603d36786"),
                            ClassroomId = new Guid("51024c7b-3fb4-49e0-b907-485f4adb6435"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9380),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("4ede55af-128e-4a3e-be59-a43651fd1fe1"),
                            ClassroomId = new Guid("d10fdbdf-b229-435f-82cc-347c09a7c8be"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9380),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("28b0c5c0-2543-4689-ab87-490250a25daa"),
                            ClassroomId = new Guid("03403da8-e010-4490-87f2-0d406ee95e44"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9380),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("2963f30a-cf0e-48ed-8347-29a3fba963dd"),
                            ClassroomId = new Guid("2516201c-236f-4071-ae4f-0163b60d945e"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9390),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("9911969c-b7ea-449f-a776-b0f480cf5233"),
                            ClassroomId = new Guid("cf5300fb-1880-443d-a731-80682c7a889d"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9390),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("a1fc0cab-0bcf-4ffe-8a85-d527cf9654ef"),
                            ClassroomId = new Guid("5e366b30-082b-4aab-93a2-1bb70bb2d10c"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9390),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("ff7a0174-d8bb-46e4-8ad0-12a8acacd610"),
                            ClassroomId = new Guid("f2425a1e-0433-4508-aed4-3f63f3a148f2"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9390),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("33aff1d4-d530-4c74-82d2-6a786703b085"),
                            ClassroomId = new Guid("80f8dce5-662a-4c5a-86ed-98da8643109d"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9400),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("1e47f410-f1ea-45bd-ba9a-6441ac90d128"),
                            ClassroomId = new Guid("a60a6ac1-99e7-468d-bcd3-c3b6d3bf215d"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9400),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("3551551d-a10f-4d99-a4ba-6a05af29776b"),
                            ClassroomId = new Guid("b7abc369-e304-4e18-a953-c148beac05d8"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9400),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("d093b930-cfb9-465d-9e34-b6b9ad423d53"),
                            ClassroomId = new Guid("8224b0a9-9cc6-43d8-9acc-98c5d7db6f89"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9400),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("433417e6-a2fa-4940-bb0a-0a597f8ccc0b"),
                            ClassroomId = new Guid("7ae880b6-0914-4b1e-b276-7fb7af52a19f"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9410),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("16fccf53-8d29-46c4-9f2c-39f6192461db"),
                            ClassroomId = new Guid("6413d3a2-4e85-4c18-b7aa-6e33d14e7638"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9410),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("968098d5-3eb9-4c74-b16b-e8c8db3a68a2"),
                            ClassroomId = new Guid("2d10b0f7-182d-4ec6-9fd6-59890a5c2c6c"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9410),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("03e5d627-2c15-4769-8d48-9e4e6aaa44ad"),
                            ClassroomId = new Guid("a28105ec-9132-47d2-b769-c4472e41b4df"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9420),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("bcaf5e67-6f0b-4aa6-be64-efa85a2b57f5"),
                            ClassroomId = new Guid("6254a611-5cc5-4b71-b6f6-d53351c7bb44"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9420),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("733c5a63-4f43-48a6-8cbd-5b56c9d07186"),
                            ClassroomId = new Guid("600cae99-cafb-4d82-92cb-286d88a8fed5"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9420),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("a8456133-3b2f-49b8-8bd9-e670c16f55b4"),
                            ClassroomId = new Guid("d7d60ae3-2253-47eb-b8d2-592ff3eff606"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9420),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("ccba6b5b-8d93-4339-a037-698be89acc34"),
                            ClassroomId = new Guid("ecf56071-7ce2-430f-a2e1-219b3804a23e"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9430),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("ee6b85d6-463b-457e-ad17-c5197ae40877"),
                            ClassroomId = new Guid("4fbcdace-7d82-422f-a517-f28a22247222"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9430),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("648d5ad5-b363-4f42-b9f6-289737050acc"),
                            ClassroomId = new Guid("40d13ea5-1f8c-4390-82b0-fc6ab0b047e5"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9430),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("2bac4e68-a481-4fbb-96da-cff7ff595cde"),
                            ClassroomId = new Guid("1e37ba0d-e660-4d32-9f3e-1f355dab53d1"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9430),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("f9d99718-18cf-4639-b5bf-dad49bfda9e2"),
                            ClassroomId = new Guid("1eb75642-ba0f-4072-a7c2-f2d9f7df2c07"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9440),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("7c92d805-6b65-41a2-8498-ee5d25391dfe"),
                            ClassroomId = new Guid("e60c9e86-ef8e-4f45-ac07-4e6078df11f0"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9440),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("99456a00-107f-49c9-a2cc-6fe2256e9831"),
                            ClassroomId = new Guid("d3f30e56-1492-4f05-b3cb-f28b8830c6c9"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9440),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("ba849c6a-7aef-47f3-b308-93ab1b7e69da"),
                            ClassroomId = new Guid("48a31bc3-8078-40b8-807f-b0a1b08f2d94"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9440),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("34530c6d-9a03-47d8-a459-1b2ba29c540e"),
                            ClassroomId = new Guid("25a765bc-66a8-4411-b1ca-1be8a5b5c37d"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9450),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("d7429847-a55e-44e1-8c03-47931205ac3a"),
                            ClassroomId = new Guid("1d62e2b8-97b6-4207-8f61-39357b9b7499"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9450),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("78598b48-ee00-45ce-a516-0f7a60c0e256"),
                            ClassroomId = new Guid("e2990d44-ca16-4f23-9aa1-203c47e11b13"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9450),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("0528628c-dc5a-4726-bd44-b262032657db"),
                            ClassroomId = new Guid("aa4b69ec-024b-4f23-bb61-dd1f8982e0de"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9450),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("11cb9a71-3456-4c24-8b52-7fc808674ee2"),
                            ClassroomId = new Guid("949542b2-14e5-4944-aa15-db194000003b"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9460),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("8099dac5-e65f-415a-b04e-751981e80b43"),
                            ClassroomId = new Guid("ebd66a9e-0813-4d77-9498-f66933d46412"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9460),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("1b908a53-926a-48f2-9eb8-a0d0d9e5987a"),
                            ClassroomId = new Guid("72d8f80c-e611-4af9-889e-8e4c5d870b74"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9460),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("ec533196-0a01-43fa-932e-efeadf26080b"),
                            ClassroomId = new Guid("47cef1b2-77df-4a3f-971a-13ac866934c2"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9470),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("e4c78987-e6b8-4f5f-914b-78f217547039"),
                            ClassroomId = new Guid("44bdcfcd-7501-45f8-b181-012ee37c1ce1"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9470),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("f620328b-17b1-428b-b6d8-9d313ffc5108"),
                            ClassroomId = new Guid("84e3da95-9372-4af6-b4c4-64c397c4fb96"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9470),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("7075149f-5d8d-490a-b011-a826c43c3648"),
                            ClassroomId = new Guid("b779915d-52df-4e0d-8173-bfde01304a48"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9470),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("facb7047-f20d-403f-a6eb-7fb98b88e042"),
                            ClassroomId = new Guid("bc386832-bad5-429b-a350-eb3a5b9063e8"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9480),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("550385de-f3e3-4ae4-b1cf-072ec63d6cf2"),
                            ClassroomId = new Guid("db4002f8-2661-4cdd-b377-dd017e779462"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9480),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("538d6844-dbe3-4c24-a982-b3e6c8a7b327"),
                            ClassroomId = new Guid("741be67c-e1c9-447f-ba7f-7aa8f4c3c5f8"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9490),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("8b907038-3ba8-44ea-ab0c-26bb426240aa"),
                            ClassroomId = new Guid("bf497f2a-a004-4abf-9e1d-36f1659c189a"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9490),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("3002824a-67e6-421e-9266-47a01bd346b0"),
                            ClassroomId = new Guid("eb3820d2-a6da-4ac4-a403-b3bd8a0c8d4a"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9490),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("c5371275-8055-4160-bf5d-6bd56a24dc07"),
                            ClassroomId = new Guid("fb1e4faf-a95e-451c-99b9-373177f0651f"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9500),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("5479ae66-ccb2-48fc-8ac3-722219429050"),
                            ClassroomId = new Guid("f000260e-fb82-4b2c-84a6-eba34cd5f1f5"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9500),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("00095c41-05b6-428d-b3bd-1e61fe781fb0"),
                            ClassroomId = new Guid("304ce9d5-6ff6-4a62-b418-ab4988cd659b"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9500),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("56483076-c325-45bf-8cca-4c969550e590"),
                            ClassroomId = new Guid("a690bd67-4949-4382-b2bd-a4cd6dd0b0f7"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9500),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("a37af81c-d648-4080-b9c8-1ca3fd104389"),
                            ClassroomId = new Guid("1fd9d87e-7176-4242-a1a2-302724e6a1ec"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9510),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("4c85b5a7-350d-4bd7-993a-af2598f070b3"),
                            ClassroomId = new Guid("734788b2-5bfc-4d76-897c-40a918106c16"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9510),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("522cd84f-9af5-463d-87c5-b2e52eddff6e"),
                            ClassroomId = new Guid("b2a855f1-6263-4c54-83d7-24d30d280563"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9510),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("e35c0559-e0bd-46e7-bd74-31a35f978c95"),
                            ClassroomId = new Guid("6acc7531-cc7a-4ab6-87de-d2f7af5d6329"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9510),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("6d6ff562-c133-47f2-b014-42608f305786"),
                            ClassroomId = new Guid("d06ca3f8-a3e1-4cfa-8925-44d007dc4db3"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9520),
                            KeyStatus = 0
                        },
                        new
                        {
                            Id = new Guid("cf5ebb7a-65af-4804-a3ed-308dd1d1019d"),
                            ClassroomId = new Guid("66a27a07-a8d5-43ae-be6c-f8690c013f94"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 493, DateTimeKind.Utc).AddTicks(9520),
                            KeyStatus = 0
                        });
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.KeyRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("EndDateOfRecurrence")
                        .HasColumnType("date");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("UserId");

                    b.ToTable("KeyRequests");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.RegistrationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RegistrationRequests");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.TransferKeyRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("KeyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KeyId");

                    b.HasIndex("RecipientId");

                    b.ToTable("TransferKeyRequests");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<int?>("UserRole")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("06fbbf6d-d7c3-4501-b634-17f72e4124d9"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 32, DateTimeKind.Utc).AddTicks(5410),
                            Email = "admin@gmail.com",
                            FullName = "admin",
                            Gender = 0,
                            Password = "$2a$11$.uCUo9hzeamgVWoafg7vS.Q2SrWWo7WmbInsug7Xqpu75cWyztDYW",
                            UserRole = 3
                        },
                        new
                        {
                            Id = new Guid("056f5c1c-5738-4730-b762-f6558ad2fb73"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 142, DateTimeKind.Utc).AddTicks(9830),
                            Email = "dean@gmail.com",
                            FullName = "dean",
                            Gender = 0,
                            Password = "$2a$11$nkZlBbgn/1BNu1D8AyBD4umvEan8aUflTekR7L60pDO2.mRDZHoXK",
                            UserRole = 2
                        },
                        new
                        {
                            Id = new Guid("b63b35d3-f277-4f6a-9277-27a55a88f930"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 262, DateTimeKind.Utc).AddTicks(8220),
                            Email = "teacher@gmail.com",
                            FullName = "teacher",
                            Gender = 0,
                            Password = "$2a$11$EgvUsRnyCrtv53u1R9wak.iuZM.xnyCe8AoRd0rVZdx8PK7MGwU3m",
                            UserRole = 1
                        },
                        new
                        {
                            Id = new Guid("5ca1bc07-a59b-49c2-8c5f-ee3ed827ed4d"),
                            CreateTime = new DateTime(2024, 3, 10, 4, 57, 6, 378, DateTimeKind.Utc).AddTicks(4270),
                            Email = "student@gmail.com",
                            FullName = "student",
                            Gender = 0,
                            Password = "$2a$11$ss74ukx6vtCb..cxCQZDquQkmxXErfuQQ.N/aWPL1dYIgBR25nLgu",
                            UserRole = 0
                        });
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.Key", b =>
                {
                    b.HasOne("ClassroomBooking.Domain.Entities.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassroomBooking.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Classroom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.KeyRequest", b =>
                {
                    b.HasOne("ClassroomBooking.Domain.Entities.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassroomBooking.Domain.Entities.User", "User")
                        .WithMany("Requests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.RegistrationRequest", b =>
                {
                    b.HasOne("ClassroomBooking.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.TransferKeyRequest", b =>
                {
                    b.HasOne("ClassroomBooking.Domain.Entities.Key", "Key")
                        .WithMany()
                        .HasForeignKey("KeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassroomBooking.Domain.Entities.User", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Key");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("ClassroomBooking.Domain.Entities.User", b =>
                {
                    b.Navigation("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
